### ISSUE TITLE
Requesting help for LG Air purifier

### ISSUE THREAD

**Issue by merv2k4** [nVuln/homebridge-lg-thinq#102]
Hi I have two air purifyers, seems having issue not showing up in homekit. Pls see below log. Thanks

[11/16/2021, 2:00:39 AM] Homebridge v1.3.6 (HAP v0.9.7) (Homebridge F2D4) is running on port 51705.
[11/16/2021, 2:00:40 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[11/16/2021, 2:00:40 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[11/16/2021, 2:00:42 AM] [LGThinQ] Successfully connected to the ThinQ API.
[11/16/2021, 2:00:43 AM] [LGThinQ] [master room purifier] Setting up device!
[11/16/2021, 2:00:43 AM] [LGThinQ] Restoring existing accessory: 1afc3db1-a92f-1c6c-ae10-24e853217c44: master room purifier (AIR_PURIFIER AS60GDWV0.AQAR)
[11/16/2021, 2:00:43 AM] [LGThinQ] [Air Purifier] Setting up device!
[11/16/2021, 2:00:43 AM] [LGThinQ] Restoring existing accessory: f82011d1-ebfe-1a67-a723-f8b95a57eb3f: Air Purifier (AIR_PURIFIER AIR_910604_WW)
[11/16/2021, 2:00:43 AM] [LGThinQ] Start MQTT listener for thinq2 device
[11/16/2021, 2:00:44 AM] [LGThinQ] Successfully connected to the MQTT server.
[11/16/2021, 2:00:52 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[11/16/2021, 2:00:52 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[11/16/2021, 2:01:22 AM] [Homebridge UI] [homebridge-lg-thinq] Terminating child process...
[11/16/2021, 2:01:22 AM] [Homebridge UI] [homebridge-lg-thinq] Child process ended

**Comment by merv2k4** [comment]
Debug log below:

[11/16/2021, 2:04:07 AM] Homebridge v1.3.6 (HAP v0.9.7) (Homebridge F2D4) is running on port 51705.
[11/16/2021, 2:04:07 AM] [LGThinQ] [request] get https://route.lgthinq.com:46030/v1/service/application/gateway-uri
[11/16/2021, 2:04:08 AM] [LGThinQ] [request] post https://kic.lgthinq.com:46030/api/common/gatewayUriList
[11/16/2021, 2:04:08 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[11/16/2021, 2:04:08 AM] [homebridge-lg-thinq] Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at RotationSpeed.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1982:16)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1535:21)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at RotationSpeed.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:38)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2139:22)
[11/16/2021, 2:04:08 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[11/16/2021, 2:04:08 AM] [homebridge-lg-thinq] Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at RotationSpeed.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1982:16)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1535:21)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at RotationSpeed.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:38)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2139:22)
[11/16/2021, 2:04:08 AM] [LGThinQ] [request] post https://sg.lgeapi.com/oauth2/token
[11/16/2021, 2:04:09 AM] [LGThinQ] [request] post https://kic.lgthinq.com:46030/api/member/login
[11/16/2021, 2:04:09 AM] [LGThinQ] [request] get https://sg.lgeapi.com/users/profile
[11/16/2021, 2:04:09 AM] [LGThinQ] Successfully connected to the ThinQ API.
[11/16/2021, 2:04:10 AM] [LGThinQ] [request] get https://kic-service.lgthinq.com:46030/v1/service/homes
[11/16/2021, 2:04:10 AM] [LGThinQ] [request] get https://kic-service.lgthinq.com:46030/v1/service/homes/163699742035383979
[11/16/2021, 2:04:10 AM] [LGThinQ] [request] get https://kic-service.lgthinq.com:46030/v1/service/homes/161217925670443821
[11/16/2021, 2:04:10 AM] [LGThinQ] Device data:  {"deviceId":"1afc3db1-a92f-1c6c-ae10-24e853217c44","deviceType":402,"modelName":"AIR_910604_WW","subModelNm":null,"sensorType":null,"alias":"master room purifier","deviceCode":"LI02","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"AIR_TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"merv_S1","timezoneCode":"Asia/Singapore","timezoneCodeAlias":"Asia/Singapore","sdsGuide":"{\"deviceCode\":\"LI02\"}","newRegYn":"Y","remoteControlType":"","fareTarget":null,"area":"300597","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210511055652000","regIndex":0,"blackboxYn":"Y","groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","snapshot":{"airState.windStrength":8,"airState.miscFuncState.airFast":0,"airState.tempState.unit":0,"airState.diagCode":0,"mid":1886437894,"airState.miscFuncState.watertankLight":0,"airState.lightingState.signal":1,"airState.quality.sensorMon":0,"airState.miscFuncState.antiBugs":0,"airState.quality.odor":1,"airState.tempState.target":0,"airState.humidity.current":30,"airState.filterMngStates.useTimeTop":4000,"airState.miscFuncState.airUVDisinfection":0,"airState.operation":1,"airState.reservation.absoluteStopTime":0,"airState.wMode.humidification":0,"timestamp":1636998719179,"airState.quality.PM10":8,"static":{"deviceType":"402","countryCode":"SG"},"airState.filterMngStates.maxTimeTop":4000,"airState.quality.overall":1,"airState.tempState.current":40,"airState.miscFuncState.airRemoval":0,"airState.reservation.sleepTime":0,"airState.filterMngStates.desorption":0,"airState.reservation.absoluteStartTime":0,"airState.miscFuncState.cleanDry":0,"airState.reservation.targetTimeToStart":0,"meta":{"allDeviceInfoUpdate":false,"messageId":"8GVcl8I5SY6WxTHQMjslyQ"},"airState.quality.PM1":8,"airState.circulate.rotate":0,"airState.quality.PM2":8,"online":true,"airState.opMode":16,"airState.reservation.targetTimeToStop":0,"airState.filterMngStates.maxTime":4000,"airState.filterMngStates.useTime":3208,"airState.circulate.strength":8},"manufacture":{"inventoryOrg":"DLZ","macAddress":"24:E8:53:21:7C:44","manufacturedAt":"2021-04-13T08:56:25.000000+0000","salesModel":"AS60GDWV0.AQAR","manufactureModel":"AS60GDWV0.AQAR","registeredAt":"2021-04-14T03:00:20.594767+0000","serialNo":"104KAMZ0LA71"},"online":true,"platformType":"thinq2","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"N","modelJsonVer":"11.75","modelJsonUri":"https://objectcontent.lgthinq.com/0e88386f-9d2c-4a33-a955-845e9d0bc927?hdnts=exp=1694360537~hmac=d1b8feb95780dec36d154730326e3710d33d7befd21d64a886377b826d99d802","appModuleVer":"6.26","appModuleUri":"https://objectcontent.lgthinq.com/64e1799f-ebc6-40d5-be3f-a5da236eb094?hdnts=exp=1692841091~hmac=58da68817a5596b875cea58c23c970e30dae4b006a4b3d142bdfb2f1c7854743","appRestartYn":"Y","appModuleSize":"16031930","langPackProductTypeVer":"29.29","langPackProductTypeUri":"https://objectcontent.lgthinq.com/dcf911c9-5fde-4bb1-aa70-0800cf966f08?hdnts=exp=1699666296~hmac=2e0cfcbaa16d80ab15118640b6740d3cdb07060f482ff53938836d33759ac4fd","langPackModelVer":null,"langPackModelUri":null,"roomId":"","fwInfoList":[{"checksum":"000052C7","partNumber":"SAA38365230","order":3},{"checksum":"00002FF8","partNumber":"SAA38131264","order":2},{"checksum":"00003FC8","partNumber":"SAA38799124","order":1}],"modemInfo":{"modelName":"AIR_910604_WW","appVersion":"clip_hna_v1.9.116","modemType":"QCOM_QCA4010","ruleEngine":"y"},"existsEntryPopup":"N","fwVer":null,"modemVer":"clip_hna_v1.9.094","subDeviceCount":0,"firebaseLogKey":"P:MD-T:G1-F:B","cardType":"Small","cardControl":"Base","detailDeviceCode":null,"upgradableYn":"N"}
[11/16/2021, 2:04:10 AM] [LGThinQ] [master room purifier] Setting up device!
[11/16/2021, 2:04:10 AM] [LGThinQ] Restoring existing accessory: 1afc3db1-a92f-1c6c-ae10-24e853217c44: master room purifier (AIR_PURIFIER AS60GDWV0.AQAR)
[11/16/2021, 2:04:10 AM] [LGThinQ] Device data:  {"deviceId":"b9f192e5-295e-1d54-8894-402f86e4c6a7","deviceType":203,"modelName":"S3BF_POD_DN4","subModelNm":null,"sensorType":null,"alias":"Styler","deviceCode":"LA04","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"L2MM","timezoneCode":"Asia/Singapore","timezoneCodeAlias":"Asia/Singapore","sdsGuide":"{\"deviceCode\":\"LA04\"}","newRegYn":"Y","remoteControlType":"","fareTarget":null,"area":"300597","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210202175002000","regIndex":0,"blackboxYn":"Y","groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","snapshot":{"mid":525324067,"online":true,"styler":{"initialBit":"INITIAL_BIT_OFF","reserveTimeMinute":0,"initialTimeMinute":0,"preState":"COMPLETE","energyMonitoring":681,"error":"ERROR_NO","nightDry":"NIGHTDRY_OFF","remainTimeMinute":1,"reserveTimeHour":0,"smartCourse":"NONE","currentDownloadCourse4":0,"childLock":"CHILDLOCK_OFF","remainTimeHour":0,"remoteStart":"REMOTE_START_OFF","currentDownloadCourse1":"BABY_CLOTHING_SANITARY","course":"NONE","currentDownloadCourse3":0,"currentDownloadCourse2":66,"state":"POWEROFF","currentDownloadCourseCount":1,"initialTimeHour":0},"static":{"deviceType":"203","countryCode":"SG"},"meta":{"allDeviceInfoUpdate":true,"messageId":"RKst80vMTXW7p7PPfg5o3Q"},"timestamp":1636961582594},"manufacture":null,"online":true,"platformType":"thinq2","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"N","modelJsonVer":"51.6","modelJsonUri":"https://objectcontent.lgthinq.com/1762d6bf-d076-43d1-97f6-6f7bb89fd2b2?hdnts=exp=1675997742~hmac=f7ea2c55ad32ca82c79a7aa32bc766cd1f57b64231319d39ae6de5515f345a4a","appModuleVer":"3.64","appModuleUri":"https://objectcontent.lgthinq.com/6dc5b4dd-dea5-4f83-8317-490045cd1309?hdnts=exp=1690505351~hmac=a5da0252db8458259829b35d72d8760b3dc1409433745774fb3b2cca7982391b","appRestartYn":"Y","appModuleSize":"9896549","langPackProductTypeVer":"51.72","langPackProductTypeUri":"https://objectcontent.lgthinq.com/1643e708-6488-4c01-b62d-6044b35efd6c?hdnts=exp=1699401411~hmac=8275eb079c19f96f53098f76e92317460c5d7cb0369c9dd5bdacb0b8fb086914","langPackModelVer":null,"langPackModelUri":null,"roomId":"","fwInfoList":[{"checksum":"000046E3","partNumber":"SAA37569132","order":2},{"checksum":"00001678","partNumber":"SAA37569015","order":1}],"modemInfo":{"modelName":"S3BF_POD_DN4","appVersion":"clip_hna_v1.9.116","modemType":"QCOM_QCA4010","ruleEngine":"y"},"existsEntryPopup":"N","fwVer":null,"modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:ST-S:ST-U:SLIM-P:ESSENCE","cardType":"Small","cardControl":"Base","detailDeviceCode":null,"upgradableYn":"N"}
[11/16/2021, 2:04:10 AM] [LGThinQ] Device skipped:  b9f192e5-295e-1d54-8894-402f86e4c6a7
[11/16/2021, 2:04:10 AM] [LGThinQ] Device data:  {"deviceId":"f82011d1-ebfe-1a67-a723-f8b95a57eb3f","deviceType":402,"modelName":"AIR_910604_WW","subModelNm":null,"sensorType":null,"alias":"Air Purifier","deviceCode":"LI02","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"AIR_TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"merv_S1","timezoneCode":"Asia/Singapore","timezoneCodeAlias":"Asia/Singapore","sdsGuide":"{\"deviceCode\":\"LI02\"}","newRegYn":"Y","remoteControlType":"","fareTarget":null,"area":"300597","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210508062040000","regIndex":0,"blackboxYn":"Y","groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","snapshot":{"airState.windStrength":8,"airState.miscFuncState.airFast":0,"airState.tempState.unit":0,"airState.diagCode":0,"mid":1860310592,"airState.miscFuncState.watertankLight":0,"airState.lightingState.signal":1,"airState.quality.sensorMon":0,"airState.miscFuncState.antiBugs":0,"airState.quality.odor":1,"airState.tempState.target":0,"airState.humidity.current":30,"airState.filterMngStates.useTimeTop":2879,"airState.miscFuncState.airUVDisinfection":0,"airState.operation":1,"airState.reservation.absoluteStopTime":0,"airState.wMode.humidification":0,"timestamp":1636997950185,"airState.quality.PM10":8,"static":{"deviceType":"402","countryCode":"SG"},"airState.filterMngStates.maxTimeTop":4000,"airState.quality.overall":1,"airState.tempState.current":40,"airState.miscFuncState.airRemoval":1,"airState.reservation.sleepTime":0,"airState.filterMngStates.desorption":0,"airState.reservation.absoluteStartTime":0,"airState.miscFuncState.cleanDry":0,"airState.reservation.targetTimeToStart":0,"meta":{"allDeviceInfoUpdate":false,"messageId":"cgk8FV1AR8ejOBqIQzhm0g"},"airState.quality.PM1":8,"airState.circulate.rotate":0,"airState.quality.PM2":8,"online":true,"airState.opMode":16,"airState.reservation.targetTimeToStop":0,"airState.filterMngStates.maxTime":4000,"airState.filterMngStates.useTime":3574,"airState.circulate.strength":8},"manufacture":null,"online":true,"platformType":"thinq2","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"N","modelJsonVer":"11.75","modelJsonUri":"https://objectcontent.lgthinq.com/2c08d5c9-63a6-410f-871e-ca8c73b2e415?hdnts=exp=1694360537~hmac=44f98e61869c32f05b68428f7d58c709ee770dbe4b93800fd73c53fa01568754","appModuleVer":"6.26","appModuleUri":"https://objectcontent.lgthinq.com/64e1799f-ebc6-40d5-be3f-a5da236eb094?hdnts=exp=1692841091~hmac=58da68817a5596b875cea58c23c970e30dae4b006a4b3d142bdfb2f1c7854743","appRestartYn":"Y","appModuleSize":"16031930","langPackProductTypeVer":"29.29","langPackProductTypeUri":"https://objectcontent.lgthinq.com/dcf911c9-5fde-4bb1-aa70-0800cf966f08?hdnts=exp=1699666296~hmac=2e0cfcbaa16d80ab15118640b6740d3cdb07060f482ff53938836d33759ac4fd","langPackModelVer":null,"langPackModelUri":null,"roomId":"","fwInfoList":[{"checksum":"000052C7","partNumber":"SAA38365230","order":3},{"checksum":"00003618","partNumber":"SAA38131265","order":2},{"checksum":"00003B07","partNumber":"SAA38799122","order":1}],"modemInfo":{"modelName":"AIR_910604_WW","appVersion":"clip_hna_v1.9.116","modemType":"QCOM_QCA4010","ruleEngine":"y"},"existsEntryPopup":"N","fwVer":null,"modemVer":"clip_hna_v1.9.080","subDeviceCount":0,"firebaseLogKey":"P:MD-T:G2-F:B","cardType":"Small","cardControl":"Base","detailDeviceCode":null,"upgradableYn":"N"}
[11/16/2021, 2:04:10 AM] [LGThinQ] [Air Purifier] Setting up device!
[11/16/2021, 2:04:10 AM] [LGThinQ] Restoring existing accessory: f82011d1-ebfe-1a67-a723-f8b95a57eb3f: Air Purifier (AIR_PURIFIER AIR_910604_WW)
[11/16/2021, 2:04:10 AM] [LGThinQ] Start MQTT listener for thinq2 device
[11/16/2021, 2:04:11 AM] [LGThinQ] [request] get https://common.lgthinq.com/route
[11/16/2021, 2:04:11 AM] [LGThinQ] [request] get https://www.amazontrust.com/repository/AmazonRootCA1.pem
[11/16/2021, 2:04:12 AM] [LGThinQ] [request] post https://kic-service.lgthinq.com:46030/v1/service/users/client
[11/16/2021, 2:04:12 AM] [LGThinQ] [request] post https://kic-service.lgthinq.com:46030/v1/service/users/client/certificate
[11/16/2021, 2:04:12 AM] [LGThinQ] open mqtt connection to ssl://a3phael99lf879-ats.iot.ap-northeast-2.amazonaws.com:8883
[11/16/2021, 2:04:13 AM] [LGThinQ] Successfully connected to the MQTT server.
[11/16/2021, 2:04:13 AM] [LGThinQ] mqtt connected: ssl://a3phael99lf879-ats.iot.ap-northeast-2.amazonaws.com:8883
[11/16/2021, 2:04:18 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[11/16/2021, 2:04:18 AM] [homebridge-lg-thinq] Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at RotationSpeed.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1982:16)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1535:21)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at RotationSpeed.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:38)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2139:22)
[11/16/2021, 2:04:18 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[11/16/2021, 2:04:18 AM] [homebridge-lg-thinq] Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at RotationSpeed.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1982:16)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1535:21)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at RotationSpeed.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:38)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2139:22)
[11/16/2021, 2:04:32 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[11/16/2021, 2:04:32 AM] [homebridge-lg-thinq] Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at RotationSpeed.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1982:16)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1535:21)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at RotationSpeed.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:38)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2139:22)
[11/16/2021, 2:04:32 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[11/16/2021, 2:04:32 AM] [homebridge-lg-thinq] Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at RotationSpeed.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1982:16)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1535:21)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at RotationSpeed.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:38)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2139:22)

**Comment by merv2k4** [comment]
Update: It took some time before the devices showed up in homekit

1) Air Quality is showing unknown
2) I can power off/on device without issue
3) when i schedule the purifyer to start from LG app, it shows starting in homekit and it did not detect the mode/speed of the purifier. But when I stopped and start it in homekit, it 
[air purifyer log.txt](https://github.com/nVuln/homebridge-lg-thinq/files/7540802/air.purifyer.log.txt)
works well and I can set the mode to auto.
4) the oscillate  function is not working

Pls find the attached debug log. Thank you

**Comment by merv2k4** [comment]
Screenshots from homekit from one of the air purifyer

![WhatsApp Image 2021-11-16 at 2 19 31 AM (1)](https://user-images.githubusercontent.com/78693962/141834067-4fef3def-e674-43b2-aa73-e7d45fecab56.jpeg)
![WhatsApp Image 2021-11-16 at 2 19 31 AM](https://user-images.githubusercontent.com/78693962/141834074-62886fee-1ff0-4639-8998-97dc9f482a5a.jpeg)
![WhatsApp Image 2021-11-16 at 2 19 32 AM (1)](https://user-images.githubusercontent.com/78693962/141834076-cfde1a18-8d1b-48fa-9eec-637cf3fafd8f.jpeg)
![WhatsApp Image 2021-11-16 at 2 19 32 AM](https://user-images.githubusercontent.com/78693962/141834080-acee813a-b09e-4060-af5c-953ea2805e93.jpeg)
![WhatsApp Image 2021-11-16 at 2 19 33 AM](https://user-images.githubusercontent.com/78693962/141834084-9fd22e25-8414-4113-ae67-63941e761bd4.jpeg)
[air purifyer log.txt](https://github.com/nVuln/homebridge-lg-thinq/files/7540832/air.purifyer.log.txt)

**Comment by merv2k4** [comment]
Homebridge Config:

{
    "bridge": {
        "name": "Homebridge F2D4",
        "username": "0E:4E:A3:34:F2:D4",
        "port": 51705,
        "pin": "031-45-154",
        "advertiser": "bonjour-hap",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "country": "SG",
            "language": "en-SG",
            "auth_mode": "token",
            "refresh_token": "xxx",
            "username": "xxx",
            "password": "xxx",
            "devices": [
                {
                    "id": "xxx",
                    "name": "master room purifier",
                    "type": "AIR_PURIFIER"
                },
                {
                    "id": "xxx",
                    "name": "Air Purifier",
                    "type": "AIR_PURIFIER"
                }
            ],
            "thinq1": true,
            "refresh_interval": 60,
            "platform": "LGThinQ"
        }
    ]
}

**Comment by nVuln** [comment]
> 1. Air Quality is showing unknown

I'll investigate this issue and update later

> 3. when i schedule the purifyer to start from LG app, it shows starting in homekit and it did not detect the mode/speed of the purifier. But when I stopped and start it in homekit, it
>    [air purifyer log.txt](https://github.com/nVuln/homebridge-lg-thinq/files/7540802/air.purifyer.log.txt)
>    works well and I can set the mode to auto.

you can set schedule in Homekit automation, do not use LG app feature together with Homekit (it's may cause some unwanted error)

> 4. the oscillate  function is not working

oscillate only worked in manual mode, I saw you always use auto mode (not sure if your device working like this, you can try turn on SWING while AUTO is on via LG app and see if it's work)

**Comment by merv2k4** [comment]
Hi nVuln,

tested and Its working if i control thru the app. Thanks.

Does your plugin supports LG Styler too?

Thanks again!

**Comment by nVuln** [comment]
> 

at the moment this plugin do not support styler, if you have styler, can can open new issue and upload all device data, I'll try my best to implement it
