### ISSUE TITLE
I have got a problem about authenticationError: Already in use by 3rd-Party Registeration:GGL

### ISSUE THREAD

**Issue by Neoplanetz** [nVuln/homebridge-lg-thinq#11]
**Describe The Bug:**
I have got a problem about authenticationError: Already in use by 3rd-Party Registeration:GGL.
I usually log on LG Thinq App with Google Email. so I installed this plug-in and configured My account setting.
but I have got a log about authenticationError: Already in use by 3rd-Party Registeration:GGL. how can I fix it?
Is it not support 3rd-Party log in LG Thinq App?

**Logs:**
[5/13/2021, 1:36:13 PM] [LGThinQ] AuthenticationError: Already in use by 3rd-Party Registeration:GGL
    at /homebridge/node_modules/homebridge-lg-thinq/src/lib/Auth.ts:57:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Auth.login (/homebridge/node_modules/homebridge-lg-thinq/src/lib/Auth.ts:51:17)
    at API.ready (/homebridge/node_modules/homebridge-lg-thinq/src/lib/API.ts:144:22)
    at ThinQ.isReady (/homebridge/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:122:7)
    at LGThinQHomebridgePlatform.discoverDevices (/homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:65:47)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:49:7)

**Plugin Config:**

```json
{
            "username": "n*********@gmail.com",
            "password": "*****!",
            "country": "KR",
            "language": "ko-KR",
            "platform": "LGThinQ"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-lg-thinq v0.2.2-test.10
* **Homebridge Version**: v1.3.4
* **Node.js Version**: v14.16.1
* **NPM Version**: 6.14.12
* **Operating System**: Docker

**Comment by nVuln** [comment]
at this time we only support login by LG account
I'm currently working to support 3rd login, please wait for future update
