### ISSUE TITLE
Installation error regarding npm

### ISSUE THREAD

**Issue by jonas240** [nVuln/homebridge-lg-thinq#12]
**Describe Your Problem:**
Hi, I'm trying to install your plugin. However, it fails while providing a npm error message. What am I doing wrong? I never encountered that one before.

Thank you so much for publishing this plugin and your help!
Regards, Jonas

**Logs:**

```
17.5.2021, 16:59:31 npm
17.5.2021, 16:59:31  ERR! code ETARGET
17.5.2021, 16:59:31 npm
17.5.2021, 16:59:31 ERR! notarget No matching version found for qs@^6.10.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR!
17.5.2021, 16:59:31 notarget a package version that doesn't exist.
```

**Environment:**

* **Plugin Version**: 0.2.3
* **Homebridge Version**:  1.3.3
* **HOOBS Version**: 3.3.5
* **Node.js Version**:  14.16.0 LTS
* **NPM Version**:  7.6.3
* **Operating System**: Raspbian

**Comment by nVuln** [comment]
I don't know which js repo did you used.
but qs@6.10.1 still listed here: https://www.npmjs.com/package/qs/v/6.10.1
please try it again

**Comment by jonas240** [comment]
Hi @nVuln,
I just checked: qs (6.10.1), npm (7.16.0), and node (14.17.0) should be up-to-date. I tried to install the plugin, still no luck. I got the same log as before. For further investigation, I added the complete log of this run down below. Thank you so much for your patience!

```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--prefer-offline',
0 verbose cli   '--no-audit',
0 verbose cli   '--unsafe-perm',
0 verbose cli   '--progress=true',
0 verbose cli   'homebridge-lg-thinq@0.2.4'
0 verbose cli ]
1 info using npm@7.16.0
2 info using node@v14.17.0
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 6ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/hoobs/.hoobs/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/hoobs/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 2ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 3ms
17 timing config:load:setEnvs Completed in 3ms
18 timing config:load Completed in 26ms
19 timing npm:load:configload Completed in 27ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 2ms
22 timing npm:load:cleanupLog Completed in 6ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 40ms
26 timing config:load:flatten Completed in 8ms
27 timing arborist:ctor Completed in 2ms
28 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
29 timing idealTree:init Completed in 2420ms
30 timing idealTree:userRequests Completed in 8ms
31 silly idealTree buildDeps
32 silly fetch manifest homebridge-lg-thinq@0.2.4
33 http fetch GET 200 https://registry.npmjs.org/homebridge-lg-thinq 2807ms (cache stale)
34 silly placeDep ROOT homebridge-lg-thinq@ OK for: @hoobs/hoobs@3.3.5 want: 0.2.4
35 timing idealTree:#root Completed in 2836ms
36 timing idealTree:node_modules/homebridge-lg-thinq Completed in 0ms
37 timing idealTree:buildDeps Completed in 2840ms
38 timing idealTree:fixDepFlags Completed in 74ms
39 timing idealTree Completed in 5347ms
40 timing command:install Completed in 5401ms
41 verbose type version
42 verbose stack homebridge-lg-thinq: No matching version found for homebridge-lg-thinq@0.2.4.
42 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
42 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
42 verbose stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:934:19)
42 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:880:11)
42 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
42 verbose stack     at async Promise.all (index 1)
42 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:136:5)
42 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:150:5)
43 verbose cwd /home/hoobs/.hoobs
44 verbose Linux 5.10.17-v7l+
45 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--prefer-offline" "--no-audit" "--unsafe-perm" "--progress=true" "homebridge-lg-thinq@0.2.4"
46 verbose node v14.17.0
47 verbose npm  v7.16.0
48 error code ETARGET
49 error notarget No matching version found for homebridge-lg-thinq@0.2.4.
50 error notarget In most cases you or one of your dependencies are requesting
50 error notarget a package version that doesn't exist.
51 verbose exit 1
```

**Comment by nVuln** [comment]
try clean npm cache with command
`npm cache clean --force`
