### ISSUE TITLE
Dishwasher D30: Cannot read properties of undefined (reading 'remainTimeHour')

### ISSUE THREAD

**Issue by bc1980** [nVuln/homebridge-lg-thinq#130]
**Describe The Bug:**
On launch of Homebridge, the following erroring is produced:
TypeError: Cannot read properties of undefined (reading 'remainTimeHour')
```
    at DishwasherStatus.get remainDuration [as remainDuration] (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/WasherDryer.ts:189:7)
    at Dishwasher.updateAccessoryCharacteristic (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Dishwasher.ts:47:21)
    at LGThinQHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-lg-thinq/src/platform.ts:163:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce:**
Add a D30 Dishwasher to config and launch Homebridge

**Expected behavior:**
No error to be produced.

**Logs:**

```
[10/02/2022, 13:02:00] [LGThinQ] Loading accessory from Homebridge cache: REFRIGERATOR
[10/02/2022, 13:02:00] [LGThinQ] Loading accessory from Homebridge cache: WASHER
[10/02/2022, 13:02:00] [LGThinQ] Loading accessory from Homebridge cache: DRYER
[10/02/2022, 13:02:00] [LGThinQ] Loading accessory from Homebridge cache: DISHWASHER
[10/02/2022, 13:02:00] [LGThinQ] Executed didFinishLaunching callback
[10/02/2022, 13:02:01] [LGThinQ] [request] get https://route.lgthinq.com:46030/v1/service/application/gateway-uri
[10/02/2022, 13:02:05] [LGThinQ] [request] post https://kic.lgthinq.com:46030/api/common/gatewayUriList
[10/02/2022, 13:02:07] [LGThinQ] [request] post https://ca.lgeapi.com/oauth2/token
[10/02/2022, 13:02:08] [LGThinQ] [request] post https://aic.lgthinq.com:46030/api/member/login
[10/02/2022, 13:02:09] [LGThinQ] [request] get https://ca.lgeapi.com/users/profile
[10/02/2022, 13:02:09] [LGThinQ] Successfully connected to the ThinQ API.
[10/02/2022, 13:02:09] [LGThinQ] [request] get https://aic-service.lgthinq.com:46030/v1/service/homes
[10/02/2022, 13:02:10] [LGThinQ] [request] get https://aic-service.lgthinq.com:46030/v1/service/homes/160044651717382627
[10/02/2022, 13:02:10] [LGThinQ] Device data:  {"deviceId":"163c9c50-15b2-11f5-93ad-0051ed3f06ab","deviceType":101,"modelName":"2REF11EIIFM__","subModelNm":null,"sensorType":null,"alias":"REFRIGERATOR","deviceCode":"KI0102","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"GalaxyIOT","timezoneCode":"America/Vancouver","timezoneCodeAlias":"USA/Vancouver","sdsGuide":"{\"deviceCode\":\"KI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"52941","sleep":null,"deviceState":"D","rmsClientId":null,"regDtUtc":"20190119082157000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"1.6","modelJsonUri":"https://aic.lgthinq.com:46030/api/webContents/modelJSON?modelName=2REF11EIIFM__&countryCode=WW&contentsId=WW21063007130974362151&authKey=thinq","appModuleVer":"303.35","appModuleUri":"https://objectcontent.lgthinq.com/d9e9cbd3-9734-4d6b-88d4-003d35cd5ca1?hdnts=exp=1703119553~hmac=9c6b7b8be633eda86867710cb8494a7e85adc22e92ac5154a595c254e49e9027","appRestartYn":"Y","appModuleSize":"8344898","langPackProductTypeVer":"51.2","langPackProductTypeUri":"https://objectcontent.lgthinq.com/5fbd9889-f5e4-449b-a2ef-076944802871?hdnts=exp=1705542680~hmac=2ca001899a311cbdf089d85198c4270f45abfa8bf916489c96a2b9bb04bdf5de","langPackModelVer":"","langPackModelUri":"","roomId":"","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"QC_Modem_1.2.79","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:RFBFFD-M:3D-P:A_MAJESTY1","cardType":"Small","cardControl":"Base","detailDeviceCode":null,"upgradableYn":null,"autoFwDownloadYn":null}
[10/02/2022, 13:02:10] [LGThinQ] [REFRIGERATOR] Setting up device!
[10/02/2022, 13:02:11] [LGThinQ] Restoring existing accessory: 163c9c50-15b2-11f5-93ad-0051ed3f06ab: REFRIGERATOR (REFRIGERATOR 2REF11EIIFM__)
[10/02/2022, 13:02:11] [LGThinQ] Device data:  {"deviceId":"53ddc7ab-33ed-11e9-b901-020000000000","deviceType":201,"modelName":"FH4G2CDYV3_USNFC","subModelNm":null,"sensorType":null,"alias":"WASHER","deviceCode":"LA02","networkType":"03","tftYn":"N","guideTypeYn":"N","guideType":"","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"","timezoneCode":"America/Vancouver","timezoneCodeAlias":"USA/Vancouver","sdsGuide":"{\"deviceCode\":\"LA02\",\"modelTypeCode\":\"\"}","newRegYn":"N","remoteControlType":null,"fareTarget":null,"area":"52941","sleep":null,"deviceState":"D","rmsClientId":null,"regDtUtc":"20190219022323000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":3,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"10","modelJsonUri":"https://aic.lgthinq.com:46030/api/webContents/modelJSON?modelName=FH4G2CDYV3_USNFC&countryCode=WW&contentsId=JS0502084930651217&authKey=thinq","appModuleVer":"6.21","appModuleUri":"https://objectcontent.lgthinq.com/ea54eb02-d923-4bf8-b6b7-6cef48783849?hdnts=exp=1705894666~hmac=da9f0fcb47f96863814304ec250639c83e7b3b5400ff0e84e7be0162df4c2f6a","appRestartYn":"Y","appModuleSize":"10013123","langPackProductTypeVer":"93.4","langPackProductTypeUri":"https://objectcontent.lgthinq.com/11dff924-572b-499f-83e6-b168331aba56?hdnts=exp=1707455795~hmac=21dd3de3af37e4df27e53addb503bd407f4881a667b133649f72d0ff74dcbfac","langPackModelVer":"","langPackModelUri":"","roomId":"","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"","modemVer":null,"subDeviceCount":0,"firebaseLogKey":null,"cardType":"Small","cardControl":"Base","detailDeviceCode":null,"upgradableYn":null,"autoFwDownloadYn":null}
[10/02/2022, 13:02:11] [LGThinQ] [WASHER] Setting up device!
[10/02/2022, 13:02:11] [LGThinQ] Restoring existing accessory: 53ddc7ab-33ed-11e9-b901-020000000000: WASHER (WASHER FH4G2CDYV3_USNFC)
[10/02/2022, 13:02:11] [LGThinQ] Device data:  {"deviceId":"7c27802c-33ed-11e9-b901-020000000000","deviceType":202,"modelName":"RV1394ES_D_US","subModelNm":null,"sensorType":null,"alias":"DRYER","deviceCode":"LA03","networkType":"03","tftYn":"N","guideTypeYn":"N","guideType":"","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"","timezoneCode":"America/Vancouver","timezoneCodeAlias":"USA/Vancouver","sdsGuide":"{\"deviceCode\":\"LA03\",\"modelTypeCode\":\"\"}","newRegYn":"N","remoteControlType":null,"fareTarget":null,"area":"52941","sleep":null,"deviceState":"D","rmsClientId":null,"regDtUtc":"20190219022430000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":4,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"6.5","modelJsonUri":"https://aic.lgthinq.com:46030/api/webContents/modelJSON?modelName=RV1394ES_D_US&countryCode=WW&contentsId=JS2016061100000941&authKey=thinq","appModuleVer":"6.21","appModuleUri":"https://objectcontent.lgthinq.com/ea54eb02-d923-4bf8-b6b7-6cef48783849?hdnts=exp=1705894666~hmac=da9f0fcb47f96863814304ec250639c83e7b3b5400ff0e84e7be0162df4c2f6a","appRestartYn":"Y","appModuleSize":"10013123","langPackProductTypeVer":"93.4","langPackProductTypeUri":"https://objectcontent.lgthinq.com/11dff924-572b-499f-83e6-b168331aba56?hdnts=exp=1707455795~hmac=21dd3de3af37e4df27e53addb503bd407f4881a667b133649f72d0ff74dcbfac","langPackModelVer":"","langPackModelUri":"","roomId":"","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"","modemVer":null,"subDeviceCount":0,"firebaseLogKey":null,"cardType":"Small","cardControl":"Base","detailDeviceCode":null,"upgradableYn":null,"autoFwDownloadYn":null}
[10/02/2022, 13:02:11] [LGThinQ] [DRYER] Setting up device!
[10/02/2022, 13:02:12] [LGThinQ] Restoring existing accessory: 7c27802c-33ed-11e9-b901-020000000000: DRYER (DRYER RV1394ES_D_US)
[10/02/2022, 13:02:12] [LGThinQ] Device data:  {"deviceId":"a1e49a5d-33ed-11e9-b901-020000000000","deviceType":301,"modelName":"FH4755L","subModelNm":null,"sensorType":null,"alias":"OVEN","deviceCode":"KI03","networkType":"03","tftYn":"N","guideTypeYn":"N","guideType":"","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"","timezoneCode":"America/Vancouver","timezoneCodeAlias":"USA/Vancouver","sdsGuide":"{\"deviceCode\":\"KI03\",\"modelTypeCode\":\"\"}","newRegYn":"N","remoteControlType":null,"fareTarget":null,"area":"52941","sleep":null,"deviceState":"D","rmsClientId":null,"regDtUtc":"20190219022534000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":5,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"1","modelJsonUri":"https://aic.lgthinq.com:46030/api/webContents/modelJSON?modelName=FH4755L&countryCode=WW&contentsId=JS2015080100000223&authKey=thinq","appModuleVer":"2.17","appModuleUri":"https://objectcontent.lgthinq.com/77d7d342-0a40-43ac-8a3f-de745f778d1f?hdnts=exp=1691543423~hmac=06b51bc8bf1885e2bb8da04f58a318824e072e6fde86f4bfff0c48347dcaeb7f","appRestartYn":"Y","appModuleSize":"16564764","langPackProductTypeVer":"41.0","langPackProductTypeUri":"https://objectcontent.lgthinq.com/4e3cb446-05e3-4157-8bb4-cae588c640f8?hdnts=exp=1702452645~hmac=c289319ac662481e22913ce60062689ca92dd06055987a8c6e488b70014a7a2f","langPackModelVer":"","langPackModelUri":"","roomId":"161957710108566825","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"","modemVer":null,"subDeviceCount":0,"firebaseLogKey":null,"cardType":"Small","cardControl":"Base","detailDeviceCode":null,"upgradableYn":null,"autoFwDownloadYn":null}
[10/02/2022, 13:02:12] [LGThinQ] [OVEN] Setting up device!
[10/02/2022, 13:02:13] [LGThinQ] Device not supported: a1e49a5d-33ed-11e9-b901-020000000000: OVEN (OVEN FH4755L)
[10/02/2022, 13:02:13] [LGThinQ] Device data:  {"deviceId":"e5640060-c9c4-11e8-ad7e-0051ed7e87ef","deviceType":204,"modelName":"D30","subModelNm":null,"sensorType":null,"alias":"DISHWASHER","deviceCode":"KI06","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"GalaxyIOT","timezoneCode":"America/Vancouver","timezoneCodeAlias":"USA/Vancouver","sdsGuide":"{\"deviceCode\":\"KI06\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"52941","sleep":null,"deviceState":"D","rmsClientId":null,"regDtUtc":"20190119082715000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":2,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"2.4","modelJsonUri":"https://aic.lgthinq.com:46030/api/webContents/modelJSON?modelName=D30&countryCode=WW&contentsId=JS1110063222474666&authKey=thinq","appModuleVer":"210.52","appModuleUri":"https://objectcontent.lgthinq.com/d21de0d4-637f-470d-a6be-536242e1d01b?hdnts=exp=1687928055~hmac=2fff599740f7a7bfa2177b201a34d98b8c0eadfd112f0232a77a353af46f1cae","appRestartYn":"Y","appModuleSize":"21341322","langPackProductTypeVer":"33.0","langPackProductTypeUri":"https://objectcontent.lgthinq.com/24b8d119-0843-4165-94c0-2719ccc97aed?hdnts=exp=1706323364~hmac=6874c528698f3458932a6410a4a3036b7e72de6bce0d8932eef3885c3d56d83b","langPackModelVer":"","langPackModelUri":"","roomId":"161957710108566825","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"QC_Modem_1.2.80","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:DW-B:LG-C:BuiltUn-Fn:SX","cardType":"Small","cardControl":"Base","detailDeviceCode":null,"upgradableYn":null,"autoFwDownloadYn":null}
[10/02/2022, 13:02:13] [LGThinQ] [DISHWASHER] Setting up device!
[10/02/2022, 13:02:13] [LGThinQ] a1e49a5d-33ed-11e9-b901-020000000000 - unregistered!
[10/02/2022, 13:02:13] [LGThinQ] Restoring existing accessory: e5640060-c9c4-11e8-ad7e-0051ed7e87ef: DISHWASHER (DISHWASHER D30)
[10/02/2022, 13:02:13] [LGThinQ] Cannot read properties of undefined (reading 'remainTimeHour')
[10/02/2022, 13:02:13] [LGThinQ] TypeError: Cannot read properties of undefined (reading 'remainTimeHour')
    at DishwasherStatus.get remainDuration [as remainDuration] (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/WasherDryer.ts:189:7)
    at Dishwasher.updateAccessoryCharacteristic (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Dishwasher.ts:47:21)
    at LGThinQHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-lg-thinq/src/platform.ts:163:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Plugin Config:**

```
            {
            "country": "CA",
            "language": "en-CA",
            "auth_mode": "token",
            "refresh_token": "<REDACTED>",
            "username": "<REDACTED>",
            "password": "<REDACTED>",
            "platform": "LGThinQ",
            "devices": [
                {
                    "id": "163c9c50-15b2-11f5-93ad-0051ed3f06ab",
                    "name": "REFRIGERATOR",
                    "type": "REFRIGERATOR",
                    "ref_express_freezer": true
                },
                {
                    "id": "53ddc7ab-33ed-11e9-b901-020000000000",
                    "name": "WASHER",
                    "type": "WASHER"
                },
                {
                    "id": "7c27802c-33ed-11e9-b901-020000000000",
                    "name": "DRYER",
                    "type": "DRYER"
                },
                {
                    "id": "a1e49a5d-33ed-11e9-b901-020000000000",
                    "name": "OVEN",
                    "type": "OVEN"
                },
                {
                    "id": "e5640060-c9c4-11e8-ad7e-0051ed7e87ef",
                    "name": "DISHWASHER",
                    "type": "DISHWASHER"
                }
            ],
            "thinq1": true,
            "refresh_interval": 60
        }
```

**Environment:**

* **Plugin Version**:1.2.13
* **Homebridge Version**: 1.4.0
* **Node.js Version**: 16.13.1
* **NPM Version**: 6.14.15
* **Operating System**: Raspbian

**Comment by nVuln** [comment]
can you try install `v1.2.14-test.5` and see if it's worked ?

**Comment by bc1980** [comment]
@nVuln Success! No more error message after installing `v1.2.14-test.5`. Thank you so much for the prompt response!
