### ISSUE TITLE
request error:  TokenExpiredError: Not logged in -- occurs on v1 devices, about 1h after starting homebridge

### ISSUE THREAD

**Issue by vfontes** [nVuln/homebridge-lg-thinq#159]
**Describe Your Problem:**
After about one hour of starting homebridge, it is no longer possible to control v1 devices.

A homebridge restart solves the issue until it occurs again.

**Logs:**

```
[27/04/2022, 22:40:38] [LGThinQ] [request] post https://kic.lgthinq.com:46030/api/common/gatewayUriList
[27/04/2022, 22:40:38] [LGThinQ] [request] post https://br.lgeapi.com/oauth/1.0/oauth2/token
[27/04/2022, 22:40:39] [LGThinQ] request error:  TokenExpiredError: Not logged in.
    at client.interceptors.response.use.err.response._a (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/request.ts:37:13)
    at API.request (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:59:12)
    at /usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:65:18
    at /usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:64:16
    at API.request (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:59:12)
    at API.postRequest (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:48:12)
    at API.thinq1PostRequest (/usr/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:274:12)
    at AC.setActive (/usr/lib/node_modules/homebridge-lg-thinq/src/v1/devices/AC.ts:64:5)
```

**Plugin Config:**

```json
{
    "country": "BR",
    "language": "pt-BR",
    "auth_mode": "token",
    "refresh_token": "REDACTED",
    "username": "REDACTED",
    "password": "REDACTED",
    "devices": [
        {
            "id": "07a5d9f6-0a02-1a49-b60c-44cb8b77ae62",
            "name": "Escritório AC",
            "type": "AC",
            "ac_mode": "BOTH",
            "ac_swing_mode": "VERTICAL"
        },
        {
            "id": "8d54ebef-c244-1cc7-8404-402f867b2522",
            "name": "Lavadora",
            "type": "WASHER"
        },
        {
            "id": "d27c5030-7149-11d3-80b3-7440be56f323",
            "name": "Quarto AC",
            "type": "AC",
            "ac_mode": "BOTH",
            "ac_swing_mode": "VERTICAL",
            "ac_temperature_sensor": true
        },
        {
            "id": "d27dfde0-7149-11d3-80be-7440be9260fa",
            "name": "Sala AC",
            "type": "AC",
            "ac_mode": "BOTH",
            "ac_swing_mode": "VERTICAL"
        }
    ],
    "thinq1": true,
    "refresh_interval": 60,
    "platform": "LGThinQ"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.15
* **Homebridge Version**: 1.4.0
* **Node.js Version**: 16.13.1 
* **NPM Version**: 8.1.2 
* **Operating System**: Raspbian 10.3

**Comment by KanzakiRanko1** [comment]
Same here, except I error out whenever Homebridge launches. Tried getting a new token manually and logging to another account to no avail. 

I also get those right at launch: 
```
[4/29/2022, 3:11:56 AM] [LGThinQ] Please open the native LG App and sign in to your account to see what happened, maybe new agreement need your accept. Then try restarting Homebridge.
[4/29/2022, 3:11:56 AM] [LGThinQ] MonitorError: 0110 - 약관동의 미동의 상태입니다.
    at client.interceptors.response.use.err.response._a (/homebridge/node_modules/homebridge-lg-thinq/src/lib/request.ts:39:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Auth.getJSessionId (/homebridge/node_modules/homebridge-lg-thinq/src/lib/Auth.ts:211:12)
    at API.ready (/homebridge/node_modules/homebridge-lg-thinq/src/lib/API.ts:251:25)
    at ThinQ.isReady (/homebridge/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:295:5)
```

Environment:

Plugin Version: 1.2.15
Homebridge Version: 1.4.0
Node.js Version: 16.13.2
NPM Version: 8.8.0
Operating System: Ubuntu 18.04.6 LTS (current official Homebridge Docker image running inside a boot2docker Hyper-V VM in a Windows 11 Pro box)

**Comment by vfontes** [comment]
I eventually downgraded the plugin back to 1.2.14 and the issue went away, so it might be something specific to 1.2.15.

**Comment by KanzakiRanko1** [comment]
1.2.14 gives me the same issue; in fact, I upgraded to 1.2.15 as an attempt to solve it :(

**Comment by shonsj** [comment]
Currently, I'm having same issue on mine... Any guys find the way to fix it out?

**Comment by kenin031** [comment]
same here.. (1.2.15)

**Comment by stefxx** [comment]
Having the same issue...

**Comment by nVuln** [comment]
guys, please try `v1.2.17-test.1`, hope it work

**Comment by nVuln** [comment]
> Thanks for your support sir. But on 1.2.17-test.1, found some added fuction "turbo mode" on air purifier. could you please check whether its for air purifier or not. Whenever I turn on the mode, nothing has been changed on air purifier.
> 
> Thx

hmm.. is your model AIR_910604_WW? I have people request this feature for his air purifier, it's "Air Fast", your model do not support it?
so just ignore it right now, in next release I'll add a config to enable/disable it

**Comment by shonsj** [comment]
Yes. My one is AIR_910604_WW. Have no idea whether it works properly or not. But one thing i can sure there is no diff visibly when turning on the turbo mode.

**Comment by vfontes** [comment]
Running `v1.2.17-test.1` for a couple of hours now, and so far so good! No error messages and I can still control v1 and v2 AC units.

**Comment by shonsj** [comment]
> > Thanks for your support sir. But on 1.2.17-test.1, found some added fuction "turbo mode" on air purifier. could you please check whether its for air purifier or not. Whenever I turn on the mode, nothing has been changed on air purifier.
> > Thx
> 
> hmm.. is your model AIR_910604_WW? I have people request this feature for his air purifier, it's "Air Fast", your model do not support it? so just ignore it right now, in next release I'll add a config to enable/disable it


here is my log following after turning on the turbo mode
[6/15/2022, 8:21:53 PM] [homebridge-lg-thinq] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Cannot read properties of null (reading 'AirFast'). See https://homebridge.io/w/JtMGR for more info.
[6/15/2022, 8:21:53 PM] [homebridge-lg-thinq] TypeError: Cannot read properties of null (reading 'AirFast')
    at On.getHandler (/usr/local/lib/node_modules/homebridge-lg-thinq/src/v1/devices/AirPurifier.ts:72:60)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1528:32)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:16)
    at On.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:689:38)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1569:27)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
