### ISSUE TITLE
TypeError: axios_1.default.create is not a function

### ISSUE THREAD

**Issue by Aidenkwok** [nVuln/homebridge-lg-thinq#168]
**Describe The Bug:**
Unable to install and configure the plugin. 

**To Reproduce:**
Search for plugin on UI. Click install, click settings. Shows spinning cog.

**Expected behavior:**
Bring up config setttings

**Logs:**

```
[homebridge-lg-thinq] /var/lib/homebridge/node_modules/.pnpm/homebridge-lg-thinq@1.2.16/node_modules/homebridge-lg-thinq/dist/lib/request.js:10
const client = axios_1.default.create();
                               ^

TypeError: axios_1.default.create is not a function
    at Object.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/homebridge-lg-thinq@1.2.16/node_modules/homebridge-lg-thinq/dist/lib/request.js:10:32)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/homebridge-lg-thinq@1.2.16/node_modules/homebridge-lg-thinq/dist/lib/API.js:30:19)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
```

**Plugin Config:**
N/A

**Environment:**

* **Plugin Version**: v1.2.16
* **Homebridge Version**: 1.4.1
* **Node.js Version**: 15.14.0
* **NPM Version**: 
* **Operating System**: hb-service

**Comment by nVuln** [comment]
please try using nodejs LTS version, node 14.x or 16.x

**Comment by Aidenkwok** [comment]
the issue still persists with node 14.x or 16.x

**Comment by nVuln** [comment]
hmm, not sure what happened, look like it's nodejs issue, I using nodejs v16.15.1 and it's working fine, never see this error before
