### ISSUE TITLE
Minimum temperature for heat pump should be 60F and max should be 86F

### ISSUE THREAD

**Issue by zporges** [nVuln/homebridge-lg-thinq#203]
**Describe The Bug:**
In the ThinQ app, the minimum temperature is 60F, and the maximum temperature is 86F. However, in the Home app (or with Siri)  with this plugin, the minimum temperature is 64F, and the maximum temperature is 84F. Please adjust the min/max to 60/86, in line with the ThinQ app.

**To Reproduce:**
Try to set the temperature from the Home app or from Siri, observe that temperature cannot be set below 64F or above 84F.

**Expected behavior:**
It should be possible to set the temperature to 60F or to 86F

**Logs:**

```
Show the Homebridge logs here (make sure homebridge DEBUG mode is turned `on`), remove any sensitive information.
```

**Plugin Config:**

```
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by nVuln** [comment]
can you turn on homebridge debug mode and upload some debug logging? (device data should appear in debug logging)

**Comment by zporges** [comment]
Here are some logs - thanks so much!

```
[11/30/2022, 10:16:06 PM] [LGThinQ] mqtt err: Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
[11/30/2022, 10:16:06 PM] [LGThinQ] MQTT disconnected, retrying in 60 seconds!
[11/30/2022, 10:16:08 PM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 16 exceeded minimum of 18. See https://homebridge.io/w/JtMGR for more info.
[11/30/2022, 10:16:08 PM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 16 exceeded minimum of 18. See https://homebridge.io/w/JtMGR for more info.
[11/30/2022, 10:16:08 PM] [LGThinQ] Successfully connected to the MQTT server.
[11/30/2022, 10:17:07 PM] [LGThinQ] Successfully connected to the MQTT server.
[11/30/2022, 10:17:29 PM] [Homebridge UI] Homebridge restart request received
[11/30/2022, 10:17:29 PM] [Homebridge UI] Sending SIGTERM to process...
[11/30/2022, 10:17:29 PM] [HB Supervisor] Stopping services...
[11/30/2022, 10:17:29 PM] Got SIGTERM, shutting down Homebridge...
[11/30/2022, 10:17:34 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[11/30/2022, 10:18:04 PM] [HB Supervisor] Homebridge Storage Path: /Users/porges/.homebridge
[11/30/2022, 10:18:04 PM] [HB Supervisor] Homebridge Config Path: /Users/porges/.homebridge/config.json
[11/30/2022, 10:18:04 PM] [HB Supervisor] Logging to /Users/porges/.homebridge/homebridge.log
[11/30/2022, 10:18:04 PM] [HB Supervisor] OS: Darwin 19.6.0 x64
[11/30/2022, 10:18:04 PM] [HB Supervisor] Node.js v16.16.0 /usr/local/bin/node
[11/30/2022, 10:18:04 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[11/30/2022, 10:18:04 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[11/30/2022, 10:19:06 PM] [Homebridge UI] Homebridge Config UI X v4.50.2 is listening on :: port 8581
[11/30/2022, 10:19:07 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[11/30/2022, 10:19:07 PM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 26338
[11/30/2022, 10:19:11 PM] Loaded config.json with 0 accessories and 2 platforms.
[11/30/2022, 10:19:11 PM] Loaded 4 cached accessories from cachedAccessories.
[11/30/2022, 10:19:11 PM] ---
[11/30/2022, 10:19:12 PM] Loaded plugin: homebridge-config-ui-x@4.50.2
[11/30/2022, 10:19:12 PM] Registering platform 'homebridge-config-ui-x.config'
[11/30/2022, 10:19:12 PM] ---
[11/30/2022, 10:19:14 PM] Loaded plugin: homebridge-lg-thinq@1.2.19
[11/30/2022, 10:19:14 PM] Registering platform 'homebridge-lg-thinq.LGThinQ'
[11/30/2022, 10:19:14 PM] ---
[11/30/2022, 10:19:14 PM] Loading 2 platforms...
[11/30/2022, 10:19:14 PM] [LGThinQ] Initializing LGThinQ platform...
[11/30/2022, 10:19:14 PM] [LGThinQ] Loading accessory from Homebridge cache: Master Bedroom
[11/30/2022, 10:19:14 PM] [LGThinQ] Loading accessory from Homebridge cache: Downstairs
[11/30/2022, 10:19:14 PM] [LGThinQ] Loading accessory from Homebridge cache: Office
[11/30/2022, 10:19:14 PM] [LGThinQ] Loading accessory from Homebridge cache: Up.Small Bedroom
[11/30/2022, 10:19:14 PM] [LGThinQ] Executed didFinishLaunching callback
[11/30/2022, 10:19:14 PM] Publishing bridge accessory (name: Homebridge 9E2E, publishInfo: {
  username: '0E:0E:87:56:9E:2E',
  port: 51675,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'bonjour-hap'
}).
Setup Payload:
X-HM://0024U9W2GGIZ3
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
    *redacted*    
                       
[11/30/2022, 10:19:14 PM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge 9E2E) is running on port 51675.
[11/30/2022, 10:19:14 PM] [LGThinQ] [request] get https://route.lgthinq.com:46030/v1/service/application/gateway-uri
[11/30/2022, 10:19:15 PM] [LGThinQ] [request] post https://kic.lgthinq.com:46030/api/common/gatewayUriList
[11/30/2022, 10:19:16 PM] [LGThinQ] [request] post https://us.lgeapi.com/oauth/1.0/oauth2/token
[11/30/2022, 10:19:17 PM] [LGThinQ] [request] post https://aic.lgthinq.com:46030/api/member/login
[11/30/2022, 10:19:17 PM] [LGThinQ] [request] get https://us.lgeapi.com/users/profile
[11/30/2022, 10:19:17 PM] [LGThinQ] Successfully connected to the ThinQ API.
[11/30/2022, 10:19:17 PM] [LGThinQ] [request] get https://aic-service.lgthinq.com:46030/v1/service/homes
[11/30/2022, 10:19:18 PM] [LGThinQ] [request] get https://aic-service.lgthinq.com:46030/v1/service/homes/165946075291749744
[11/30/2022, 10:19:18 PM] [LGThinQ] Device data:  {"deviceId":"36c64e84-76c6-1a1c-8d18-1c39294bc641","deviceType":401,"modelName":"RAC_056905_WW","subModelNm":null,"sensorType":null,"alias":"Master Bedroom","deviceCode":"AI01","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"RAC_TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"The Loft","timezoneCode":"America/New_York","timezoneCodeAlias":"USA/New_York","sdsGuide":"{\"deviceCode\":\"AI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"329548","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20220802210505000","regIndex":0,"blackboxYn":"Y","groupableYn":"Y","controllableYn":"Y","combinedProductYn":"N","masterYn":"Y","snapshot":{"airState.windStrength":8,"airState.wMode.lowHeating":0,"airState.diagCode":0,"airState.lightingState.displayControl":0,"airState.wDir.hStep":0,"mid":1299654434,"airState.energy.onCurrent":0,"airState.wMode.airClean":0,"airState.quality.sensorMon":0,"airState.miscFuncState.antiBugs":0,"airState.tempState.target":23,"airState.miscFuncState.autoDryRemainTime":0,"airState.operation":1,"airState.wMode.jet":0,"airState.wDir.vStep":0,"timestamp":1669863318469,"airState.powerSave.basic":0,"airState.quality.PM10":0,"fwUpgradeInfo":{"upgSched":{"upgUtc":"0","cmd":"none"}},"static":{"deviceType":"401","countryCode":"US"},"airState.quality.overall":0,"airState.tempState.current":26,"airState.miscFuncState.extraOp":0,"airState.reservation.sleepTime":0,"airState.miscFuncState.autoDry":0,"airState.reservation.targetTimeToStart":0,"meta":{"allDeviceInfoUpdate":false,"messageId":"9Z7SKYhgQjK66n4StCRr0w"},"airState.quality.PM1":0,"airState.quality.PM2":0,"online":true,"airState.opMode":4,"airState.reservation.targetTimeToStop":0,"airState.filterMngStates.maxTime":360,"airState.filterMngStates.useTime":1},"manufacture":null,"online":true,"platformType":"thinq2","homeDeviceOrder":4,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"12.34","modelJsonUri":"https://objectcontent.lgthinq.com/2053b086-ed33-4df9-a8db-546f65cd02be?hdnts=exp=1729698918~hmac=2e04e548688fcc70b97d5d217f98dbf7fa89cd75adf5cf1be984e30cd92d5326","appModuleVer":"17.78","appModuleUri":"https://objectcontent.lgthinq.com/6f9e5106-2098-4fff-8382-44224a29519d?hdnts=exp=1701394617~hmac=5b9c7381ced9740f199fbe379f86226fcb0dd261953164fbfed15b0d1bf63b7e","appRestartYn":"Y","appModuleSize":"12867303","langPackProductTypeVer":"75.7","langPackProductTypeUri":"https://objectcontent.lgthinq.com/2a06d309-a446-41a9-9c0a-9d2a60ccfdb9?hdnts=exp=1732843313~hmac=595659d1c92a53ede53974eb3d8f0f7c95dd74402d159798da1603e822ecd785","langPackModelVer":null,"langPackModelUri":null,"roomId":"","fwInfoList":[{"checksum":"00006730","order":1,"partNumber":"SAA38690428"}],"modemInfo":{"appVersion":"clip_hna_v1.9.183","modelName":"RAC_056905_WW","modemType":"RTK_RTL8711am","oneshot":"y","ruleEngine":"y","size":1572864},"existsEntryPopup":"N","fwVer":null,"modemVer":"clip_hna_v1.9.110","subDeviceCount":0,"firebaseLogKey":"P:SD","cardType":"Large","cardControl":"Control","detailDeviceCode":null,"upgradableYn":"N","autoFwDownloadYn":"N"}
[11/30/2022, 10:19:18 PM] [LGThinQ] [Master Bedroom] Setting up device!
[11/30/2022, 10:19:18 PM] [LGThinQ] Restoring existing accessory: 36c64e84-76c6-1a1c-8d18-1c39294bc641: Master Bedroom (AC RAC_056905)
[11/30/2022, 10:19:18 PM] [LGThinQ] Device data:  {"deviceId":"b111c785-9dff-13a4-a229-1c39294b9436","deviceType":401,"modelName":"RAC_056905_WW","subModelNm":null,"sensorType":null,"alias":"Downstairs","deviceCode":"AI01","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"RAC_TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"The Loft","timezoneCode":"America/New_York","timezoneCodeAlias":"USA/New_York","sdsGuide":"{\"deviceCode\":\"AI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"329548","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20220802205443000","regIndex":0,"blackboxYn":"Y","groupableYn":"Y","controllableYn":"Y","combinedProductYn":"N","masterYn":"Y","snapshot":{"airState.windStrength":8,"airState.wMode.lowHeating":0,"airState.diagCode":0,"airState.lightingState.displayControl":0,"airState.wDir.hStep":1,"mid":1300430244,"airState.energy.onCurrent":0,"airState.wMode.airClean":0,"airState.quality.sensorMon":0,"airState.miscFuncState.antiBugs":0,"airState.tempState.target":16,"airState.miscFuncState.autoDryRemainTime":0,"airState.operation":1,"airState.wMode.jet":0,"airState.wDir.vStep":0,"timestamp":1669864272286,"airState.powerSave.basic":0,"airState.quality.PM10":0,"fwUpgradeInfo":{"upgSched":{"upgUtc":"0","cmd":"none"}},"static":{"deviceType":"401","countryCode":"US"},"airState.quality.overall":0,"airState.tempState.current":26,"airState.miscFuncState.extraOp":0,"airState.reservation.sleepTime":0,"airState.miscFuncState.autoDry":0,"airState.reservation.targetTimeToStart":0,"meta":{"allDeviceInfoUpdate":false,"messageId":"21IebGkHTp2qAJxu2Dfupg"},"airState.quality.PM1":0,"airState.quality.PM2":0,"online":true,"airState.opMode":4,"airState.reservation.targetTimeToStop":0,"airState.filterMngStates.maxTime":360,"airState.filterMngStates.useTime":186},"manufacture":null,"online":true,"platformType":"thinq2","homeDeviceOrder":1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"12.34","modelJsonUri":"https://objectcontent.lgthinq.com/7789f106-9137-42d3-b665-13d2c33779f4?hdnts=exp=1729698919~hmac=ea672266a47d1c881221eba8a189b914950571b3d3a12cc13d6ce1d9c4814b56","appModuleVer":"17.78","appModuleUri":"https://objectcontent.lgthinq.com/6f9e5106-2098-4fff-8382-44224a29519d?hdnts=exp=1701394617~hmac=5b9c7381ced9740f199fbe379f86226fcb0dd261953164fbfed15b0d1bf63b7e","appRestartYn":"Y","appModuleSize":"12867303","langPackProductTypeVer":"75.7","langPackProductTypeUri":"https://objectcontent.lgthinq.com/2a06d309-a446-41a9-9c0a-9d2a60ccfdb9?hdnts=exp=1732843313~hmac=595659d1c92a53ede53974eb3d8f0f7c95dd74402d159798da1603e822ecd785","langPackModelVer":null,"langPackModelUri":null,"roomId":"","fwInfoList":[{"checksum":"0000681E","order":1,"partNumber":"SAA38690428"}],"modemInfo":{"appVersion":"clip_hna_v1.9.183","modelName":"RAC_056905_WW","modemType":"RTK_RTL8711am","oneshot":"y","ruleEngine":"y","size":1572864},"existsEntryPopup":"N","fwVer":null,"modemVer":"clip_hna_v1.9.110","subDeviceCount":0,"firebaseLogKey":"P:SD","cardType":"Large","cardControl":"Control","detailDeviceCode":null,"upgradableYn":"N","autoFwDownloadYn":"N"}
[11/30/2022, 10:19:18 PM] [LGThinQ] [Downstairs] Setting up device!
[11/30/2022, 10:19:18 PM] [LGThinQ] Restoring existing accessory: b111c785-9dff-13a4-a229-1c39294b9436: Downstairs (AC RAC_056905)
[11/30/2022, 10:19:18 PM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 16 exceeded minimum of 18. See https://homebridge.io/w/JtMGR for more info.
[11/30/2022, 10:19:18 PM] [homebridge-lg-thinq] Error: 
    at CoolingThresholdTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at CoolingThresholdTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at CoolingThresholdTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at HeaterCooler.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:795:35)
    at AirConditioner.updateAccessoryCharacteristic (/usr/local/lib/node_modules/homebridge-lg-thinq/src/devices/AirConditioner.ts:225:20)
    at LGThinQHomebridgePlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-lg-thinq/src/platform.ts:163:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11/30/2022, 10:19:18 PM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 16 exceeded minimum of 18. See https://homebridge.io/w/JtMGR for more info.
[11/30/2022, 10:19:18 PM] [homebridge-lg-thinq] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at HeatingThresholdTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at HeaterCooler.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:795:35)
    at AirConditioner.updateAccessoryCharacteristic (/usr/local/lib/node_modules/homebridge-lg-thinq/src/devices/AirConditioner.ts:226:20)
    at LGThinQHomebridgePlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-lg-thinq/src/platform.ts:163:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11/30/2022, 10:19:18 PM] [LGThinQ] Device data:  {"deviceId":"fa3ea5e6-c573-1873-ba47-1c39294bbc0c","deviceType":401,"modelName":"RAC_056905_WW","subModelNm":null,"sensorType":null,"alias":"Office","deviceCode":"AI01","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"RAC_TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"The Loft","timezoneCode":"America/New_York","timezoneCodeAlias":"USA/New_York","sdsGuide":"{\"deviceCode\":\"AI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"329548","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20220802205815000","regIndex":0,"blackboxYn":"Y","groupableYn":"Y","controllableYn":"Y","combinedProductYn":"N","masterYn":"Y","snapshot":{"airState.windStrength":8,"airState.wMode.lowHeating":0,"airState.diagCode":0,"airState.lightingState.displayControl":0,"airState.wDir.hStep":0,"mid":1297027138,"airState.energy.onCurrent":0,"airState.wMode.airClean":0,"airState.quality.sensorMon":0,"airState.miscFuncState.antiBugs":0,"airState.tempState.target":25,"airState.miscFuncState.autoDryRemainTime":0,"airState.operation":0,"airState.wMode.jet":0,"airState.wDir.vStep":100,"timestamp":1669860857952,"airState.powerSave.basic":0,"airState.quality.PM10":0,"fwUpgradeInfo":{"upgSched":{"upgUtc":"0","cmd":"none"}},"static":{"deviceType":"401","countryCode":"US"},"airState.quality.overall":0,"airState.tempState.current":24,"airState.miscFuncState.extraOp":0,"airState.reservation.sleepTime":0,"airState.miscFuncState.autoDry":0,"airState.reservation.targetTimeToStart":0,"meta":{"allDeviceInfoUpdate":false,"messageId":"BOMm1FRnTUa1uqHK1ykl6Q"},"airState.quality.PM1":0,"airState.quality.PM2":0,"online":true,"airState.opMode":4,"airState.reservation.targetTimeToStop":0,"airState.filterMngStates.maxTime":360,"airState.filterMngStates.useTime":93},"manufacture":null,"online":true,"platformType":"thinq2","homeDeviceOrder":2,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"12.34","modelJsonUri":"https://objectcontent.lgthinq.com/e6ce9cca-3f2e-4d20-974f-c4204e8318f0?hdnts=exp=1729698920~hmac=dd8795aa6440fbae4183bbd438da89d2d814190ea2e738ef80d4be8b56e505f3","appModuleVer":"17.78","appModuleUri":"https://objectcontent.lgthinq.com/6f9e5106-2098-4fff-8382-44224a29519d?hdnts=exp=1701394617~hmac=5b9c7381ced9740f199fbe379f86226fcb0dd261953164fbfed15b0d1bf63b7e","appRestartYn":"Y","appModuleSize":"12867303","langPackProductTypeVer":"75.7","langPackProductTypeUri":"https://objectcontent.lgthinq.com/2a06d309-a446-41a9-9c0a-9d2a60ccfdb9?hdnts=exp=1732843313~hmac=595659d1c92a53ede53974eb3d8f0f7c95dd74402d159798da1603e822ecd785","langPackModelVer":null,"langPackModelUri":null,"roomId":"","fwInfoList":[{"checksum":"00006730","order":1,"partNumber":"SAA38690428"}],"modemInfo":{"appVersion":"clip_hna_v1.9.183","modelName":"RAC_056905_WW","modemType":"RTK_RTL8711am","oneshot":"y","ruleEngine":"y","size":1572864},"existsEntryPopup":"N","fwVer":null,"modemVer":"clip_hna_v1.9.110","subDeviceCount":0,"firebaseLogKey":"P:SD","cardType":"Large","cardControl":"Control","detailDeviceCode":null,"upgradableYn":"N","autoFwDownloadYn":"N"}
[11/30/2022, 10:19:18 PM] [LGThinQ] [Office] Setting up device!
[11/30/2022, 10:19:18 PM] [LGThinQ] Restoring existing accessory: fa3ea5e6-c573-1873-ba47-1c39294bbc0c: Office (AC RAC_056905)
[11/30/2022, 10:19:18 PM] [LGThinQ] Device data:  {"deviceId":"fa8bf8b5-ba8b-11c8-a9cc-1c39294bfdaa","deviceType":401,"modelName":"RAC_056905_WW","subModelNm":null,"sensorType":null,"alias":"Up.Small Bedroom","deviceCode":"AI01","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"RAC_TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"The Loft","timezoneCode":"America/New_York","timezoneCodeAlias":"USA/New_York","sdsGuide":"{\"deviceCode\":\"AI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"329548","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20220802210202000","regIndex":0,"blackboxYn":"Y","groupableYn":"Y","controllableYn":"Y","combinedProductYn":"N","masterYn":"Y","snapshot":{"airState.windStrength":6,"airState.wMode.lowHeating":0,"airState.diagCode":0,"airState.lightingState.displayControl":0,"airState.wDir.hStep":0,"mid":1297027343,"airState.energy.onCurrent":0,"airState.wMode.airClean":0,"airState.quality.sensorMon":0,"airState.miscFuncState.antiBugs":0,"airState.tempState.target":30,"airState.miscFuncState.autoDryRemainTime":0,"airState.operation":0,"airState.wMode.jet":0,"airState.wDir.vStep":100,"timestamp":1669860869141,"airState.powerSave.basic":0,"airState.quality.PM10":0,"fwUpgradeInfo":{"upgSched":{"upgUtc":"0","cmd":"none"}},"static":{"deviceType":"401","countryCode":"US"},"airState.quality.overall":0,"airState.tempState.current":24,"airState.miscFuncState.extraOp":0,"airState.reservation.sleepTime":0,"airState.miscFuncState.autoDry":0,"airState.reservation.targetTimeToStart":0,"meta":{"allDeviceInfoUpdate":false,"messageId":"g3RnXVnVS82JcyMue7mPuw"},"airState.quality.PM1":0,"airState.quality.PM2":0,"online":true,"airState.opMode":4,"airState.reservation.targetTimeToStop":0,"airState.filterMngStates.maxTime":360,"airState.filterMngStates.useTime":296},"manufacture":null,"online":true,"platformType":"thinq2","homeDeviceOrder":3,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"12.34","modelJsonUri":"https://objectcontent.lgthinq.com/1e550449-9181-47f9-8806-3e43bfb9da38?hdnts=exp=1729698920~hmac=f0e4170a54af9d1db1314e07892c96f79fdc8b139c30bcf9d0169521adbbfce7","appModuleVer":"17.78","appModuleUri":"https://objectcontent.lgthinq.com/6f9e5106-2098-4fff-8382-44224a29519d?hdnts=exp=1701394617~hmac=5b9c7381ced9740f199fbe379f86226fcb0dd261953164fbfed15b0d1bf63b7e","appRestartYn":"Y","appModuleSize":"12867303","langPackProductTypeVer":"75.7","langPackProductTypeUri":"https://objectcontent.lgthinq.com/2a06d309-a446-41a9-9c0a-9d2a60ccfdb9?hdnts=exp=1732843313~hmac=595659d1c92a53ede53974eb3d8f0f7c95dd74402d159798da1603e822ecd785","langPackModelVer":null,"langPackModelUri":null,"roomId":"","fwInfoList":[{"checksum":"00006730","order":1,"partNumber":"SAA38690428"}],"modemInfo":{"appVersion":"clip_hna_v1.9.183","modelName":"RAC_056905_WW","modemType":"RTK_RTL8711am","oneshot":"y","ruleEngine":"y","size":1572864},"existsEntryPopup":"N","fwVer":null,"modemVer":"clip_hna_v1.9.110","subDeviceCount":0,"firebaseLogKey":"P:SD","cardType":"Large","cardControl":"Control","detailDeviceCode":null,"upgradableYn":"N","autoFwDownloadYn":"N"}
[11/30/2022, 10:19:18 PM] [LGThinQ] [Up.Small Bedroom] Setting up device!
[11/30/2022, 10:19:18 PM] [LGThinQ] Restoring existing accessory: fa8bf8b5-ba8b-11c8-a9cc-1c39294bfdaa: Up.Small Bedroom (AC RAC_056905)
[11/30/2022, 10:19:18 PM] [LGThinQ] Start MQTT listener for thinq2 device
[11/30/2022, 10:19:18 PM] [LGThinQ] [request] get https://common.lgthinq.com/route
[11/30/2022, 10:19:18 PM] [LGThinQ] [request] get https://www.amazontrust.com/repository/AmazonRootCA1.pem
[11/30/2022, 10:19:18 PM] [LGThinQ] [request] post https://aic-service.lgthinq.com:46030/v1/service/users/client
[11/30/2022, 10:19:19 PM] [LGThinQ] [request] post https://aic-service.lgthinq.com:46030/v1/service/users/client/certificate
[11/30/2022, 10:19:19 PM] [LGThinQ] open mqtt connection to ssl://a3phael99lf879-ats.iot.us-west-2.amazonaws.com:8883
[11/30/2022, 10:19:20 PM] [LGThinQ] Successfully connected to the MQTT server.
[11/30/2022, 10:19:20 PM] [LGThinQ] mqtt connected: ssl://a3phael99lf879-ats.iot.us-west-2.amazonaws.com:8883
[11/30/2022, 10:20:09 PM] [LGThinQ] mqtt message received: {"controlResult":{"messageId":"jsyLOtNYiKvtpmqn1Q402S","deviceId":"36c64e84-76c6-1a1c-8d18-1c39294bc641","returnCode":"0000"}}
[11/30/2022, 10:20:09 PM] [LGThinQ] [request] post https://aic-service.lgthinq.com:46030/v1/service/devices/36c64e84-76c6-1a1c-8d18-1c39294bc641/control-sync
[11/30/2022, 10:20:09 PM] [LGThinQ] [Master Bedroom] Received snapshot:  {"airState.tempState.target":29,"meta":{"allDeviceInfoUpdate":false,"messageId":"7qujiXM_T5WlLHBDVj8P-w"},"mid":1301145288,"online":true,"static":{"countryCode":"US","deviceType":"401"},"timestamp":1669864809281}
[11/30/2022, 10:20:09 PM] [LGThinQ] mqtt message received: {"data":{"state":{"reported":{"airState.tempState.target":29,"meta":{"allDeviceInfoUpdate":false,"messageId":"7qujiXM_T5WlLHBDVj8P-w"},"mid":1301145288,"online":true,"static":{"countryCode":"US","deviceType":"401"},"timestamp":1669864809281}}},"deviceId":"36c64e84-76c6-1a1c-8d18-1c39294bc641","type":"monitoring"}
[11/30/2022, 10:20:13 PM] [LGThinQ] [request] post https://aic-service.lgthinq.com:46030/v1/service/devices/36c64e84-76c6-1a1c-8d18-1c39294bc641/control-sync
[11/30/2022, 10:20:13 PM] [LGThinQ] mqtt message received: {"controlResult":{"messageId":"7wdDDPVhLVRF8PDQmi9fR4","deviceId":"36c64e84-76c6-1a1c-8d18-1c39294bc641","returnCode":"0000"}}
[11/30/2022, 10:20:13 PM] [LGThinQ] [Master Bedroom] Received snapshot:  {"airState.tempState.target":24,"meta":{"allDeviceInfoUpdate":false,"messageId":"U4I0m14zRROtsT7_uP7F3Q"},"mid":1301149548,"online":true,"static":{"countryCode":"US","deviceType":"401"},"timestamp":1669864813418}
[11/30/2022, 10:20:13 PM] [LGThinQ] mqtt message received: {"data":{"state":{"reported":{"airState.tempState.target":24,"meta":{"allDeviceInfoUpdate":false,"messageId":"U4I0m14zRROtsT7_uP7F3Q"},"mid":1301149548,"online":true,"static":{"countryCode":"US","deviceType":"401"},"timestamp":1669864813418}}},"deviceId":"36c64e84-76c6-1a1c-8d18-1c39294bc641","type":"monitoring"}

```

**Comment by nVuln** [comment]
@zporges please update to latest version and try again, hope it's worked

**Comment by zporges** [comment]
That mostly fixed the issue, thanks so much! There's still a little bit of weirdness, I suspect due to some sort of rounding issue between Celsius and Fahrenheit. I'll file a separate issue for that.

Otherwise this has been a fantastic plugin, really appreciate it.

**Comment by zporges** [comment]
@nVuln here's the other issue: https://github.com/nVuln/homebridge-lg-thinq/issues/206
