### ISSUE TITLE
Changing heating state on AC throws an error

### ISSUE THREAD

**Issue by arjanvos** [nVuln/homebridge-lg-thinq#205]
**Describe The Bug:**
An error is thrown when trying to control heating/cooling state. Works fine from LG Think app. 

**To Reproduce:**
Request the AC to heat or cool from the "accessories" tab in Homebridge or from Homekit.

**Expected behavior:**
State changes to the requested state

**Logs:**

```
[12/9/2022, 11:37:34 AM] [homebridge-lg-thinq] This plugin threw an error from the characteristic 'Target Heater-Cooler State': Unhandled error thrown inside write handler for characteristic: undefined is not a function. See https://homebridge.io/w/JtMGR for more info.
[12/9/2022, 11:37:34 AM] [homebridge-lg-thinq] TypeError: undefined is not a function
    at Array.filter (<anonymous>)
    at AirConditioner.setTargetState (/volume2/homebridge/node_modules/homebridge-lg-thinq/src/devices/AirConditioner.ts:331:8)
    at TargetHeaterCoolerState.<anonymous> (/volume2/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2547:42)
    at step (/volume2/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/volume2/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /volume2/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/volume2/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:114:16)
    at TargetHeaterCoolerState.Characteristic.handleSetRequest (/volume2/homebridge/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:871:24)
    at Bridge.<anonymous> (/volume2/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1889:29)
```

**Plugin Config:**

```
       {
            "country": "NL",
            "language": "en-NL",
            "auth_mode": "token",
            "refresh_token": "[removed]",
            "username": "",
            "password": "",
            "platform": "LGThinQ",
            "devices": [
                {
                    "id": "61d87baa-a56f-1011-be4b-4cbce98fec96",
                    "name": "AC zolder",
                    "type": "AC",
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": false,
                    "ac_humidity_sensor": false,
                    "ac_fan_control": true
                },
                {
                    "id": "af921227-df83-1fcd-b89a-4cbce9a25a2b",
                    "name": "AC woonkamer",
                    "type": "AC",
                    "ac_air_quality": false,
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": false,
                    "ac_humidity_sensor": false,
                    "ac_fan_control": true
                }
            ],
            "thinq1": false,
            "refresh_interval": 60
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.20
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 16.16.0
* **NPM Version**: 
* **Operating System**: Synology DSM 7.1

**Comment by nVuln** [comment]
please update to latest version
