### ISSUE TITLE
Cooling Threshold Temperature AND Total Consumption error

### ISSUE THREAD

**Issue by Damien514** [nVuln/homebridge-lg-thinq#226]
**Describe The Bug:**
Warnings in the logs every minute:
This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 17.8 exceeded minimum of 18.
This plugin generated a warning from the characteristic 'Total Consumption': characteristic value expected valid finite number and received "NaN" (number).

**Expected behavior:**
I think I am not supposed to get any "Total Consumption" value.

**Logs:**

```
[4/6/2023, 9:44:42 AM] [LGThinQ] [request] post https://aic.lgthinq.com:46030/api/rti/rtiMon
[4/6/2023, 9:44:42 AM] [LGThinQ] Restoring existing accessory: d27b65d0-7149-11d3-80ad-0051ed8f7866: Chambre (AC RAC_056905)
[4/6/2023, 9:44:42 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 17.8 exceeded minimum of 18. See https://homebridge.io/w/JtMGR for more info.
[4/6/2023, 9:44:42 AM] [homebridge-lg-thinq] Error: 
    at CoolingThresholdTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at CoolingThresholdTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at CoolingThresholdTemperature.Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at HeaterCooler.Service.updateCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:795:35)
    at AC.updateAccessoryCharacteristic (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/AirConditioner.ts:226:20)
    at LGThinQHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-lg-thinq/src/platform.ts:166:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[4/6/2023, 9:44:42 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 17.8 exceeded minimum of 18. See https://homebridge.io/w/JtMGR for more info.
[4/6/2023, 9:44:42 AM] [homebridge-lg-thinq] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at HeatingThresholdTemperature.Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at HeaterCooler.Service.updateCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:795:35)
    at AC.updateAccessoryCharacteristic (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/AirConditioner.ts:227:20)
    at LGThinQHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-lg-thinq/src/platform.ts:166:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[4/6/2023, 9:44:42 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Total Consumption': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[4/6/2023, 9:44:42 AM] [homebridge-lg-thinq] Error: 
    at Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2903:14)
    at Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at HeaterCooler.Service.updateCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:795:35)
    at AC.updateAccessoryCharacteristic (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/AirConditioner.ts:255:18)
    at LGThinQHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-lg-thinq/src/platform.ts:166:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[4/6/2023, 9:44:42 AM] [LGThinQ] Start MQTT listener for thinq2 device
[4/6/2023, 9:44:42 AM] [LGThinQ] [request] get https://common.lgthinq.com/route
[4/6/2023, 9:44:43 AM] [LGThinQ] [request] get https://www.amazontrust.com/repository/AmazonRootCA1.pem
[4/6/2023, 9:44:43 AM] [LGThinQ] [request] post https://aic-service.lgthinq.com:46030/v1/service/users/client
[4/6/2023, 9:44:43 AM] [LGThinQ] [request] post https://aic-service.lgthinq.com:46030/v1/service/users/client/certificate
[4/6/2023, 9:44:43 AM] [LGThinQ] open mqtt connection to ssl://a3phael99lf879-ats.iot.us-west-2.amazonaws.com:8883
[4/6/2023, 9:44:43 AM] [LGThinQ] Start polling device data every 60 second.
[4/6/2023, 9:44:44 AM] [LGThinQ] Successfully connected to the MQTT server.
[4/6/2023, 9:44:44 AM] [LGThinQ] mqtt connected: ssl://a3phael99lf879-ats.iot.us-west-2.amazonaws.com:8883

...

[4/6/2023, 9:47:44 AM] [LGThinQ] [request] post https://aic.lgthinq.com:46030/api/rti/rtiResult
[4/6/2023, 9:47:44 AM] [LGThinQ] [Chambre] Received snapshot:  {"airState.opMode":4,"airState.operation":false,"airState.tempState.current":19,"airState.tempState.target":23,"airState.windStrength":8,"airState.wDir.vStep":4,"airState.wDir.hStep":0,"airState.circulate.rotate":0,"airState.lightingState.signal":0,"airState.quality.overall":0,"airState.quality.sensorMon":0,"airState.quality.PM1":0,"airState.quality.PM2":0,"airState.quality.PM10":0,"airState.wMode.jet":0,"airState.humidity.current":0,"online":true,"raw":{"Operation":"0","OpMode":"4","WindStrength":"8","TempUnit":"NS","TempCur":"19","TempCfg":"23","GroupType":"1","SleepTime":"0","OnTime":"0","OffTime":"0","RacAddFunc":"NS","ExtraOp":"0","DiagCode":"00","TimeBsOn":"0","TimeBsOff":"0","AirClean":"0","AutoDry":"0","PowerSave":"0","WDirVStep":"4","WDirHStep":"0","TempLimitMax":"0","TempLimitMin":"0","DuctZoneType":"0","ZoneControl":"0","DRED":"0","SensorPM1":"0","SensorPM2":"0","SensorPM10":"0","AirPolution":"0","HumidityCfg":"0","WaterTempCoolMin":"0","WaterTempCoolMax":"0","WaterTempHeatMin":"0","WaterTempHeatMax":"0","HotWaterTempMin":"0","HotWaterTempMax":"0","SensorHumidity":"0","TotalAirPolution":"0","SensorMon":"0","CleanDry":"0","ProductStatus":"0","AirMonitoring":"0","Humidification":"0","AirFast":"0","AirRemoval":"0","AirUVDisinfection":"0","WatertankLight":"0","SignalLighting":"0","WDirUpDown":"0","WDirLeftRight":"0","WSwirl":"0","Jet":"0","LowHeating":"0","CirculateStrength":"0","CirculateDir":"0","AntiBugs":"0","IceValley":"0","Humsave":"0","WaterTempCur":"0","HotWaterTempCur":"0","HotWaterTempCfg":"0","HotWaterMode":"0","HotWater":"0","AWHPTempCfgSwitch":"0","AirTempCoolMin":"0","AirTempCoolMax":"0","AirTempHeatMin":"0","AirTempHeatMax":"0","WaterInTempCur":"0","AWHPWATempControlSta":"0","DisplayControl":"0","SmartCare":"0","TwoSetCoolTemp":"0","TwoSetHeatTemp":"0","TwoSetCoolUSL":"0","TwoSetCoolLSL":"0","TwoSetHeatUSL":"0","TwoSetHeatLSL":"0","TwoSetACOState":"0","TwoSetModeDeadband":"0","TwoSetState":"0"}}
[4/6/2023, 9:47:44 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Total Consumption': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[4/6/2023, 9:47:44 AM] [homebridge-lg-thinq] Error: 
    at Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2903:14)
    at Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at HeaterCooler.Service.updateCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:795:35)
    at AC.updateAccessoryCharacteristic (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/AirConditioner.ts:255:18)
    at AC.update (/usr/lib/node_modules/homebridge-lg-thinq/src/baseDevice.ts:33:10)
    at EventEmitter.emit (node:events:513:28)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lg-thinq/src/platform.ts:234:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Plugin Config:**

```
{
            "username": "xxx@yyy.ca",
            "password": "************",
            "country": "CA",
            "language": "fr-CA",
            "thinq1": true,
            "washer_trigger": true,
            "platform": "LGThinQ",
            "auth_mode": "token",
            "refresh_interval": 60,
            "refresh_token": ".*****************",
            "devices": [
                {
                    "id": "18469e1f-677d-121e-8b90-acf1080de89e",
                    "name": "Sécheuse",
                    "type": "DRYER",
                    "washer_door_lock": true
                },
                {
                    "id": "4be2e05b-b106-197f-9059-f8b95aab73df",
                    "name": "Laveuse",
                    "type": "WASHER",
                    "washer_door_lock": true
                },
                {
                    "id": "78983aaa-12ba-1088-8803-44cb8b2bc993",
                    "name": "Lili-Ambre",
                    "type": "AC",
                    "ac_mode": "BOTH",
                    "ac_temperature_sensor": false,
                    "ac_humidity_sensor": false
                },
                {
                    "id": "d27b65d0-7149-11d3-80ad-0051ed8f7866",
                    "name": "Chambre",
                    "type": "AC",
                    "ac_mode": "BOTH",
                    "ac_temperature_sensor": false,
                    "ac_humidity_sensor": false
                }
            ]
        }
```

**Environment:**

* **Plugin Version**: 1.4.0
* **Homebridge Version**: 1.6.0
* **Node.js Version**: v18.15.0
* **NPM Version**: 9.5.0
* **Operating System**: Raspbian

**Comment by Damien514** [comment]
My temperature unit is in C.
My AC (thinq1) doesn't have consumption but my washing machine an dryer (thinq2) do.

**Comment by nVuln** [comment]
I need your device data too, please look into it in debug logging, find something like this `[LGThinQ] Device data: {xxxxxx}`

**Comment by Damien514** [comment]
```
[4/6/2023, 12:10:42 PM] [LGThinQ] [request] post https://aic.lgthinq.com:46030/api/member/login
[4/6/2023, 12:10:42 PM] [LGThinQ] [request] get https://ca.lgeapi.com/users/profile
[4/6/2023, 12:10:42 PM] [LGThinQ] Successfully connected to the ThinQ API.
[4/6/2023, 12:10:43 PM] [LGThinQ] [request] get https://aic-service.lgthinq.com:46030/v1/service/homes
[4/6/2023, 12:10:44 PM] [LGThinQ] [request] get https://aic-service.lgthinq.com:46030/v1/service/homes/162293412445268286
[4/6/2023, 12:10:44 PM] [LGThinQ] Device data:  {"modelAppType":"NUTS","brandType":"common","deviceId":"18469e1f-677d-121e-8b90-acf1080de89e","deviceType":202,"modelName":"RV13B6ES_D_US_WIFI","subModelNm":null,"sensorType":null,"alias":"Sécheuse","deviceCode":"LA03","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE2","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"Foirfouille","timezoneCode":"America/Montreal","timezoneCodeAlias":"USA/Montreal","sdsGuide":"{\"deviceCode\":\"LA03\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"1365502","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210719212943000","regIndex":0,"blackboxYn":"Y","groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","snapshot":{"washerDryer":{"initialBit":"INITIAL_BIT_OFF","smartCare_onOff":"SMARTCARE_BUTTON_OFF","initialTimeMinute":1,"preState":"END","dnn_temp":"7","downloadedCourseDryer27inchBase":"SUPERDRY","energySaver":"ENERGYSAVER_OFF","error":"ERROR_NO","dryLevel":"NO_DRYLEVEL","dnn_precipitationProbability":"87","moreLessTime":0,"dnn_washingIndex":"30","dnnReady":"DNNREADY_OFF","smartCourseDryer27inchBase":"NOT_SELECTED","remainTimeHour":0,"state":"POWEROFF","reduceStatic":"REDUCESTATIC_OFF","wrinkleCare":"WRINKLECARE_OFF","temp":"NO_TEMP","antiBacterial":"ANTIBACTERIAL_OFF","loadItem":"LOADITEM_OFF","washingIndex":"30","AIDDLed":"AIDDLed_OFF","dnn_humidity":"96","dampDrySignal":"DAMPDRYSIGNAL_OFF","dnn_dust":"-","timeDry":"TIMEDRY_OFF","remainTimeMinute":1,"courseDryer27inchBase":"NOT_SELECTED","easyIron":"EASYIRON_OFF","childLock":"CHILDLOCK_OFF","remoteStart":"REMOTE_START_OFF","turboSteam":"TURBOSTEAM_OFF","initialTimeHour":0},"static":{"deviceType":"202","countryCode":"CA"},"meta":{"allDeviceInfoUpdate":true,"messageId":"GiM8weRMRUW7YspCG26gKA"},"mid":117049060,"online":true,"rules":{"wm_to_dryer_pairing_rule_02":{"lastTriggeredTime":1680628219325,"status":"INIT"}},"timestamp":1680745862381},"manufacture":null,"online":true,"platformType":"thinq2","homeDeviceOrder":1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"3.8","modelJsonUri":"https://objectcontent.lgthinq.com/d8599a26-ab3a-4a2c-85c0-61ebfe3afa59?hdnts=exp=1729749626~hmac=5855a41fe0708955ec4ac1893502f5c65d4a5f4b41705ffcb64dee1e964d6131","appModuleVer":"6.21","appModuleUri":"https://objectcontent.lgthinq.com/ea54eb02-d923-4bf8-b6b7-6cef48783849?hdnts=exp=1705894666~hmac=da9f0fcb47f96863814304ec250639c83e7b3b5400ff0e84e7be0162df4c2f6a","appRestartYn":"Y","appModuleSize":"10013123","langPackProductTypeVer":"114.0","langPackProductTypeUri":"https://objectcontent.lgthinq.com/bb356dfc-403f-4d6c-b8c9-d98c91bbc268?hdnts=exp=1743588926~hmac=0ab11fee61fbcff8410a101b9b2910fa8da6587e4b0aebe2703fbcdaa56626ca","langPackModelVer":"1.3","langPackModelUri":"https://objectcontent.lgthinq.com/ac718993-adae-4219-a179-e351ece3258d?hdnts=exp=1726567219~hmac=1bb025373d60e1bb9d3b1084cce8b161b303f5747b810f61c8c868b2bacf8f1e","roomId":"162678510145854168","fwInfoList":[{"checksum":"0000A5BB","order":2,"partNumber":"SAA38964409"},{"checksum":"0000AAD7","order":1,"partNumber":"SAA38964306"}],"modemInfo":{"appVersion":"clip_hna_v1.9.183","modelName":"RV13B6ES_D_US_WIFI","modemType":"QCOM_QCA4010","ruleEngine":"y"},"existsEntryPopup":"N","fwVer":null,"modemVer":"clip_hna_v1.9.069","subDeviceCount":0,"firebaseLogKey":"T:DR-S:27-U:0-P:VICTOR2","cardType":"Small","cardControl":"Base","detailDeviceCode":null,"upgradableYn":"N","autoFwDownloadYn":"N","homeMovableYn":"Y"}
[4/6/2023, 12:10:44 PM] [LGThinQ] [Sécheuse] Setting up device!
[4/6/2023, 12:10:44 PM] [LGThinQ] Restoring existing accessory: 18469e1f-677d-121e-8b90-acf1080de89e: Sécheuse (DRYER RV13B6ES_D_US_WIFI)
[4/6/2023, 12:10:44 PM] [LGThinQ] Device data:  {"modelAppType":"NUTS","brandType":"common","deviceId":"4be2e05b-b106-197f-9059-f8b95aab73df","deviceType":201,"modelName":"F3L7CYK5W_US_WIFI","subModelNm":null,"sensorType":null,"alias":"Laveuse","deviceCode":"LA02","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE2","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"Foirfouille","timezoneCode":"America/Montreal","timezoneCodeAlias":"USA/Montreal","sdsGuide":"{\"deviceCode\":\"LA02\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"1365502","sleep":null,"deviceState":"D","rmsClientId":null,"regDtUtc":"20220227142355000","regIndex":0,"blackboxYn":"Y","groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","snapshot":{"washerDryer":{"initialTimeMinute":0,"preState":"SPINNING","dnn_temp":"7","downloadedCourseFLUpper25inchBaseUS":"HALF_LOAD_WASH","drumLight":"DRUMLIGHT_OFF","addGarment":"ADDGARMENT_OFF","dnn_precipitationProbability":"87","dnn_washingIndex":"30","autoSoak":"AUTOSOAK_OFF","remainTimeHour":0,"opCourseFLUpper25inchBaseUS":"NOT_SELECTED","preWash":"PREWASH_OFF","apCourseFLUpper25inchBaseUS":"NOT_SELECTED","state":"END","modelHeater":"MODELHEATER_OFF","dnn_humidity":"96","freshCare":"FRESHCARE_OFF","extraRinse":"EXTRARINSE_OFF","turboWash":"TURBOWASH_OFF","remainTimeMinute":1,"delay":"DELAY_OFF","ledDataView":"LEDDATAVIEW_OFF","childLock":"CHILDLOCK_OFF","remoteStart":"REMOTE_START_OFF","extraRinseCount":"NO_EXTRARINSE","favorite":"FAVORITE_OFF","rinseSpin":"RINSE_SPIN_OFF","initialTimeHour":0,"initialBit":"INITIAL_BIT_OFF","error":"ERROR_NO","dryLevel":"NO_DRYLEVEL","washLoadDisplay":"WASHLOADDISPLAY_OFF","rinseCount":"NO_RINSE","steam":"STEAM_OFF","multiStain":"MULTISTAIN_OFF","temp":"NO_TEMP","reserveTimeMinute":0,"washingIndex":"30","TCLCount":19,"waterPlus":"WATERPLUS_OFF","smartGridEnable":"SMARTGRIDENABLE_OFF","saveEnergy":"SAVEENERGY_OFF","dnn_dust":"-","reserveTimeHour":0,"doorClose":"DOORCLOSE_ON","spin":"NO_SELECT","soilWash":"NO_SOILWASH","coldWash":"COLDWASH_OFF","loadLevel":0},"fwUpgradeInfo":{"upgSched":{"upgUtc":"0","cmd":"none"}},"static":{"deviceType":"201","countryCode":"CA"},"meta":{"allDeviceInfoUpdate":false,"messageId":"wm_to_dryer_pairing_rule_01|4be2e05b-b106-197f-9059-f8b95aab73df"},"mid":29290752,"online":false,"rules":{"wm_to_dryer_pairing_rule_01":{"lastTriggeredTime":1680621162275,"status":"INIT"}},"timestamp":1680621162177},"manufacture":null,"online":false,"platformType":"thinq2","homeDeviceOrder":2,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"12.2","modelJsonUri":"https://objectcontent.lgthinq.com/4f8b0408-72de-449f-93be-52b31f63a5b4?hdnts=exp=1711414836~hmac=d0e1e26468512cdec82885ee0f3ba2e87eaf0dde92848f873248a8d5445e78ce","appModuleVer":"6.21","appModuleUri":"https://objectcontent.lgthinq.com/ea54eb02-d923-4bf8-b6b7-6cef48783849?hdnts=exp=1705894666~hmac=da9f0fcb47f96863814304ec250639c83e7b3b5400ff0e84e7be0162df4c2f6a","appRestartYn":"Y","appModuleSize":"10013123","langPackProductTypeVer":"114.0","langPackProductTypeUri":"https://objectcontent.lgthinq.com/bb356dfc-403f-4d6c-b8c9-d98c91bbc268?hdnts=exp=1743588926~hmac=0ab11fee61fbcff8410a101b9b2910fa8da6587e4b0aebe2703fbcdaa56626ca","langPackModelVer":"6.1","langPackModelUri":"https://objectcontent.lgthinq.com/08e804c1-914b-4ef4-aafd-e0e7999a03f4?hdnts=exp=1702965614~hmac=f7fb3aca35ea7156698027c010e00175428ef37f297ef77058457c43edfd8cf6","roomId":"162678510145854168","fwInfoList":[{"checksum":"000047E3","order":2,"partNumber":"SAA41477201"},{"checksum":"0000E8F9","order":1,"partNumber":"SAA41477101"}],"modemInfo":{"appVersion":"clip_hna_v1.9.183","modelName":"F3L7CYK5W_US_WIFI","modemType":"RTK_RTL8711am","oneshot":"y","ruleEngine":"y","size":1572864},"existsEntryPopup":"N","fwVer":null,"modemVer":"clip_hna_v1.9.138","subDeviceCount":0,"firebaseLogKey":"T:FL-S:27-U:4.5-P:VICTOR2","cardType":"Small","cardControl":"Base","detailDeviceCode":null,"upgradableYn":"N","autoFwDownloadYn":"N","homeMovableYn":"Y"}
[4/6/2023, 12:10:44 PM] [LGThinQ] [Laveuse] Setting up device!
[4/6/2023, 12:10:44 PM] [LGThinQ] Restoring existing accessory: 4be2e05b-b106-197f-9059-f8b95aab73df: Laveuse (WASHER F3L7CYK5W_US_WIFI)
[4/6/2023, 12:10:44 PM] [LGThinQ] Device data:  {"modelAppType":"NUTS","brandType":"common","deviceId":"78983aaa-12ba-1088-8803-44cb8b2bc993","deviceType":401,"modelName":"RAC_056905_WW","subModelNm":null,"sensorType":null,"alias":"Lili-Ambre","deviceCode":"AI01","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"RAC_TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"Foirfouille","timezoneCode":"America/Montreal","timezoneCodeAlias":"USA/Montreal","sdsGuide":"{\"deviceCode\":\"AI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"1365502","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210811191513000","regIndex":0,"blackboxYn":"Y","groupableYn":"Y","controllableYn":"Y","combinedProductYn":"N","masterYn":"Y","snapshot":{"airState.windStrength":8,"airState.wMode.lowHeating":0,"airState.diagCode":0,"airState.lightingState.displayControl":0,"airState.wDir.hStep":0,"mid":1954478325,"airState.energy.onCurrent":0,"airState.wMode.airClean":0,"airState.quality.sensorMon":0,"airState.miscFuncState.antiBugs":0,"airState.tempState.target":23,"airState.miscFuncState.autoDryRemainTime":0,"airState.operation":0,"airState.wMode.jet":0,"airState.wDir.vStep":4,"timestamp":1680795288681,"airState.powerSave.basic":0,"airState.quality.PM10":0,"static":{"deviceType":"401","countryCode":"CA"},"airState.quality.overall":0,"airState.tempState.current":20.5,"airState.miscFuncState.extraOp":0,"airState.reservation.sleepTime":0,"airState.miscFuncState.autoDry":0,"airState.reservation.targetTimeToStart":0,"meta":{"allDeviceInfoUpdate":false,"messageId":"htJZjc1cSVSoYY8ct88LOw"},"airState.quality.PM1":0,"airState.quality.PM2":0,"online":true,"airState.opMode":4,"airState.reservation.targetTimeToStop":0,"airState.filterMngStates.maxTime":360,"airState.filterMngStates.useTime":92},"manufacture":null,"online":true,"platformType":"thinq2","homeDeviceOrder":3,"roomDeviceOrder":1,"ownershipYn":"Y","modelJsonVer":"12.43","modelJsonUri":"https://objectcontent.lgthinq.com/cd770c22-dab6-47e2-835a-3893a3846202?hdnts=exp=1741748288~hmac=27ad22455a3fb48aef362f5b3d1c84f9af48c859f18d6b73ba9d775a1ac0b135","appModuleVer":"17.78","appModuleUri":"https://objectcontent.lgthinq.com/6f9e5106-2098-4fff-8382-44224a29519d?hdnts=exp=1701394617~hmac=5b9c7381ced9740f199fbe379f86226fcb0dd261953164fbfed15b0d1bf63b7e","appRestartYn":"Y","appModuleSize":"12867303","langPackProductTypeVer":"78.1","langPackProductTypeUri":"https://objectcontent.lgthinq.com/455be37c-af0d-4790-a967-9b4bbe284da4?hdnts=exp=1737856580~hmac=d44560be55354e0ae678e6d526ab1130d65a4e557090055ac895f08c931e503f","langPackModelVer":null,"langPackModelUri":null,"roomId":"162870878003763337","fwInfoList":[{"checksum":"00006692","order":1,"partNumber":"SAA38690428"}],"modemInfo":{"appVersion":"clip_hna_v1.9.188","modelName":"RAC_056905_WW","modemType":"QCOM_QCA4010","ruleEngine":"y"},"existsEntryPopup":"N","fwVer":null,"modemVer":"clip_hna_v1.9.045","subDeviceCount":0,"firebaseLogKey":"P:SD","cardType":"Large","cardControl":"Control","detailDeviceCode":null,"upgradableYn":"N","autoFwDownloadYn":"N","homeMovableYn":"Y"}
[4/6/2023, 12:10:44 PM] [LGThinQ] [Lili-Ambre] Setting up device!
[4/6/2023, 12:10:44 PM] [LGThinQ] Restoring existing accessory: 78983aaa-12ba-1088-8803-44cb8b2bc993: Lili-Ambre (AC RAC_056905)
[4/6/2023, 12:10:44 PM] [LGThinQ] Device data:  {"modelAppType":"NUTS","brandType":"common","deviceId":"d27b65d0-7149-11d3-80ad-0051ed8f7866","deviceType":401,"modelName":"RAC_056905_CA","subModelNm":null,"sensorType":null,"alias":"Chambre","deviceCode":"AI01","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"Foirfouille","timezoneCode":"America/Montreal","timezoneCodeAlias":"USA/Montreal","sdsGuide":"{\"deviceCode\":\"AI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"1365502","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210811185732000","regIndex":0,"blackboxYn":null,"groupableYn":"Y","controllableYn":"Y","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":4,"roomDeviceOrder":1,"ownershipYn":"Y","modelJsonVer":"7.14","modelJsonUri":"https://aic.lgthinq.com:46030/api/webContents/modelJSON?modelName=modelJSON_401&countryCode=KR&contentsId=d27b65d0-7149-11d3-80ad-0051ed8f7866&authKey=thinq","appModuleVer":"17.78","appModuleUri":"https://objectcontent.lgthinq.com/6f9e5106-2098-4fff-8382-44224a29519d?hdnts=exp=1701394617~hmac=5b9c7381ced9740f199fbe379f86226fcb0dd261953164fbfed15b0d1bf63b7e","appRestartYn":"Y","appModuleSize":"12867303","langPackProductTypeVer":"78.1","langPackProductTypeUri":"https://objectcontent.lgthinq.com/455be37c-af0d-4790-a967-9b4bbe284da4?hdnts=exp=1737856580~hmac=d44560be55354e0ae678e6d526ab1130d65a4e557090055ac895f08c931e503f","langPackModelVer":"","langPackModelUri":"","roomId":"162870873159897473","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"2.5.8_RTOS_3K","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"P:SD","cardType":"Large","cardControl":"Control","detailDeviceCode":null,"upgradableYn":"N","autoFwDownloadYn":null,"homeMovableYn":"Y"}
```

**Comment by nVuln** [comment]
please update to `v1.4.1`, hope it's worked

**Comment by nVuln** [comment]
@Damien514 seem it's thinq 1 issue, I'll find a way to detect fahrenheit unit device on thinq 1, maybe add new plugin config

**Comment by nVuln** [comment]
already fixed it in latest version, please update
