### ISSUE TITLE
AC Total Consumption Error

### ISSUE THREAD

**Issue by cyberowl79** [nVuln/homebridge-lg-thinq#227]
**Describe The Bug:**
Every minute, warning log like this:
This plugin generated a warning from the characteristic 'Total Consumption': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.

**Expected behavior:**
Maybe my AC has no "Total Consumption" field.
This AC consists of one outdoor unit and several indoor units. 

**Logs:**

```
[4/10/2023, 2:11:57 AM] [LGThinQ] Restoring existing accessory: 031f5a3f-d999-166d-9ade-1c39292f2c18: 아빠서재 에어컨 (AC CST_570004)
[4/10/2023, 2:11:57 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Total Consumption': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[4/10/2023, 2:11:57 AM] [homebridge-lg-thinq] Error: 
    at Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2903:14)
    at Characteristic.updateValue (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at HeaterCooler.Service.updateCharacteristic (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:795:35)
    at AirConditioner.updateAccessoryCharacteristic (/var/lib/homebridge/node_modules/homebridge-lg-thinq/src/devices/AirConditioner.ts:255:18)
    at LGThinQHomebridgePlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:166:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Plugin Config:**

```
"devices": [
        {
            "id": "031f5a3f-d999-166d-9ade-1c39292f2c18",
            "name": "아빠서재 에어컨",
            "type": "AC",
            "ac_mode": "COOLING",
            "ac_temperature_sensor": true
        },
```

**Environment:**

* **Plugin Version**: 1.4.1
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 12.22.9
* **NPM Version**: 8.5.1
* **Operating System**: Ubuntu

**Comment by nVuln** [comment]
already fixed it in latest version, please update
