### ISSUE TITLE
Errors in log that kill the plugin

### ISSUE THREAD

**Issue by silvermy** [nVuln/homebridge-lg-thinq#26]
**Describe The Bug:**
Apparently there is no "label" attribute for refrigerator and freezer temperatures in some cases.  This kills the plugin.

**To Reproduce:**
Restart Homebridge

**Expected behavior:**
It should just work

**Logs:**

```
[12/07/2021, 10:17:30] [LGThinQ] Adding new accessory: Refrigerator
[Refrigerator@Fridge@Service Label Index] Characteristic not in required or optional characteristic section for service Thermostat. Adding anyway.
[Refrigerator@Freezer@Service Label Index] Characteristic not in required or optional characteristic section for service Thermostat. Adding anyway.
(node:14547) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'label' of undefined
    at RefrigeratorStatus.get freezerTemperature [as freezerTemperature] (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:185:58)
    at Refrigerator.updateAccessoryCharacteristic (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:73:93)
    at new Refrigerator (/usr/lib/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:58:10)
    at LGThinQHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-lg-thinq/src/platform.ts:110:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-lg-thinq/src/platform.ts:49:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14547) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:14547) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Plugin Config:**

```json
        {
            "username": "xxx@xxx.com",
            "password": "xxx",
            "country": "US",
            "language": "en-US",
            "thinq1": true,
            "washer_trigger": false,
            "platform": "LGThinQ"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v0.2.12
* **Homebridge Version**:  v1.3.3
* **Node.js Version**: v14.16.0
* **NPM Version**: 7.19.1
* **Operating System**: raspbain

**Comment by nVuln** [comment]
I already released new version to fix this issue, please update
