### ISSUE TITLE
Homebridge cashes when activating LG Think plugin

### ISSUE THREAD

**Issue by rayray4105** [nVuln/homebridge-lg-thinq#289]
Hi,

This morning I installed the plugin and used my LG Thinq credentials to login. I am able to retrieve a token and the plugin shows my washing machine and dryer. However Homebridge keeps crashing / rebooting. The following error is in the logs.

Have I done something wrong?
regards,
Raymond

 TypeError: The "path" argument must be of type string. Received function 
    at Object.join (node:path:1175:7)
    at LocalStorage.parseFile (/var/lib/homebridge/node_modules/homebridge-lg-thinq/node_modules/node-persist/src/local-storage.js:667:25)
    at LocalStorage.parseDataFile (/var/lib/homebridge/node_modules/homebridge-lg-thinq/node_modules/node-persist/src/local-storage.js:647:21)
    at LocalStorage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-lg-thinq/node_modules/node-persist/src/local-storage.js:595:44)
    at FSReqCallback.oncomplete (node:fs:194:23)

**Comment by nVuln** [comment]
what is your nodejs version?

**Comment by rayray4105** [comment]
Running v20.12.2
