### ISSUE TITLE
This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info

### ISSUE THREAD

**Issue by Basembelal** [nVuln/homebridge-lg-thinq#299]
This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info

**Comment by nVuln** [comment]
provide more debug log, device type

**Comment by Basembelal** [comment]
Please check
[21/07/2024, 16:23:34] [LGThinQ] Successfully connected to the ThinQ API.
[21/07/2024, 16:23:35] [LGThinQ] [Air Purifier] Setting up device!
[21/07/2024, 16:23:35] [LGThinQ] Restoring existing accessory: 3cd745b7-1566-1a82-9a29-1c39298b0bf1: Air Purifier (AIR_PURIFIER AIR_910604)
[21/07/2024, 16:23:35] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.

**Comment by nVuln** [comment]
turn on homebridge debug mode first, then collect all debug logging

**Comment by Basembelal** [comment]
[23/07/2024, 20:10:03] [LGThinQ] [Air Purifier] Received snapshot:  {"airState.operation":1,"airState.quality.PM1":31,"airState.quality.PM10":56,"airState.quality.PM2":41,"airState.quality.odor":1,"airState.quality.overall":3,"airState.windStrength":8,"meta":{"allDeviceInfoUpdate":false,"messageId":"wpBbaSAISZioOdpFOGV-JQ"},"mid":12913765,"online":true,"static":{"countryCode":"EG","deviceType":"402"},"timestamp":1721754602938}
[23/07/2024, 20:10:03] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[23/07/2024, 20:10:03] [homebridge-lg-thinq] Error: 
    at On.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3016:105)
    at On.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2892:12)
    at On.Characteristic.updateValue (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2333:20)
    at Lightbulb.Service.updateCharacteristic (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:804:35)
    at AirPurifier.updateAccessoryCharacteristic (/var/lib/homebridge/node_modules/homebridge-lg-thinq/src/devices/AirPurifier.ts:244:23)
    at AirPurifier.update (/var/lib/homebridge/node_modules/homebridge-lg-thinq/src/baseDevice.ts:33:10)
    at EventEmitter.emit (node:events:518:28)
    at /var/lib/homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:198:23
    at DeviceClient.<anonymous> (/var/lib/homebridge/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:291:9)
    at DeviceClient.emit (node:events:518:28)
[23/07/2024, 20:10:03] [LGThinQ] mqtt message received: {"data":{"state":{"reported":{"airState.operation":1,"airState.quality.PM1":31,"airState.quality.PM10":56,"airState.quality.PM2":41,"airState.quality.odor":1,"airState.quality.overall":3,"airState.windStrength":8,"meta":{"allDeviceInfoUpdate":false,"messageId":"wpBbaSAISZioOdpFOGV-JQ"},"mid":12913765,"online":true,"static":{"countryCode":"EG","deviceType":"402"},"timestamp":1721754602938}}},"deviceId":"3cd745b7-1566-1a82-9a29-1c39298b0bf1","type":"monitoring"}
[23/07/2024, 20:10:36] [LGThinQ] [request] post https://eic-service.lgthinq.com:46030/v1/service/devices/40cd4a91-1cc8-153f-aa97-4cbce9d8465c/control
[23/07/2024, 20:10:36] [LGThinQ] ThinQ Device Received the Command
[23/07/2024, 20:10:36] [LGThinQ] [request] post https://eic-service.lgthinq.com:46030/v1/service/devices/9f99141c-0e29-1214-a456-4cbce9cbd5cd/control
[23/07/2024, 20:10:36] [LGThinQ] ThinQ Device Received the Command
[23/07/2024, 20:10:37] [LGThinQ] [request] post https://eic-service.lgthinq.com:46030/v1/service/devices/a9b7499f-a1b8-1991-9b89-805b65dd0100/control
[23/07/2024, 20:10:37] [LGThinQ] ThinQ Device Received the Command
[23/07/2024, 20:10:37] [LGThinQ] [Khaled] Received snapshot:  {"airState.diagCode":0,"airState.energy.onCurrent":50,"airState.filterMngStates.maxTime":0,"airState.filterMngStates.useTime":0,"airState.lightingState.displayControl":1,"airState.miscFuncState.Uvnano":1,"airState.miscFuncState.antiBugs":0,"airState.miscFuncState.autoDry":0,"airState.miscFuncState.autoDryRemainTime":0,"airState.miscFuncState.extraOp":0,"airState.opMode":0,"airState.operation":0,"airState.powerSave.basic":0,"airState.quality.PM1":0,"airState.quality.PM10":0,"airState.quality.PM2":0,"airState.quality.overall":0,"airState.reservation.sleepTime":0,"airState.reservation.targetTimeToStart":0,"airState.reservation.targetTimeToStop":0,"airState.tempState.current":34.5,"airState.tempState.target":27,"airState.wDir.hStep":3,"airState.wDir.swing":0,"airState.wDir.vStep":1,"airState.wMode.airClean":0,"airState.wMode.jet":0,"airState.wMode.lowHeating":0,"airState.wMode.smartCare":0,"airState.windStrength":2,"meta":{"allDeviceInfoUpdate":false,"messageId":"Arf-TbCtQdG2Cjdaw0XKQw"},"mid":12947455,"online":true,"static":{"countryCode":"EG","deviceType":"401"},"timestamp":1721754637286}
[23/07/2024, 20:10:37] [LGThinQ] mqtt message received: {"data":{"state":{"reported":{"airState.diagCode":0,"airState.energy.onCurrent":50,"airState.filterMngStates.maxTime":0,"airState.filterMngStates.useTime":0,"airState.lightingState.displayControl":1,"airState.miscFuncState.Uvnano":1,"airState.miscFuncState.antiBugs":0,"airState.miscFuncState.autoDry":0,"airState.miscFuncState.autoDryRemainTime":0,"airState.miscFuncState.extraOp":0,"airState.opMode":0,"airState.operation":0,"airState.powerSave.basic":0,"airState.quality.PM1":0,"airState.quality.PM10":0,"airState.quality.PM2":0,"airState.quality.overall":0,"airState.reservation.sleepTime":0,"airState.reservation.targetTimeToStart":0,"airState.reservation.targetTimeToStop":0,"airState.tempState.current":34.5,"airState.tempState.target":27,"airState.wDir.hStep":3,"airState.wDir.swing":0,"airState.wDir.vStep":1,"airState.wMode.airClean":0,"airState.wMode.jet":0,"airState.wMode.lowHeating":0,"airState.wMode.smartCare":0,"airState.windStrength":2,"meta":{"allDeviceInfoUpdate":false,"messageId":"Arf-TbCtQdG2Cjdaw0XKQw"},"mid":12947455,"online":true,"static":{"countryCode":"EG","deviceType":"401"},"timestamp":1721754637286}}},"deviceId":"40cd4a91-1cc8-153f-aa97-4cbce9d8465c","type":"monitoring"}
[23/07/2024, 20:10:37] [LGThinQ] [request] get https://eic-service.lgthinq.com:46030/v1/service/homes/168709155262116366
[23/07/2024, 20:10:37] [LGThinQ] [Air Purifier] Received snapshot:  {"airState.windStrength":8,"airState.quality.PM10":56,"fwUpgradeInfo":{"upgSched":{"upgUtc":"0","cmd":"none"}},"static":{"deviceType":"402","countryCode":"EG"},"airState.quality.overall":3,"airState.diagCode":0,"airState.reservation.powerDry":0,"mid":12913765,"airState.miscFuncState.airRemoval":0,"airState.quality.sensorMon":0,"airState.quality.odor":1,"airState.reservation.absoluteStartTime":0,"airState.operation":1,"airState.reservation.absoluteStopTime":0,"meta":{"allDeviceInfoUpdate":false,"messageId":"wpBbaSAISZioOdpFOGV-JQ"},"airState.quality.PM1":31,"airState.quality.PM2":41,"online":true,"airState.opMode":9,"airState.filterMngStates.maxTime":3600,"airState.filterMngStates.useTime":2085,"timestamp":1721754602938}
[23/07/2024, 20:10:37] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[23/07/2024, 20:10:37] [homebridge-lg-thinq] Error: 
    at On.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3016:105)
    at On.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2892:12)
    at On.Characteristic.updateValue (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2333:20)
    at Lightbulb.Service.updateCharacteristic (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:804:35)
    at AirPurifier.updateAccessoryCharacteristic (/var/lib/homebridge/node_modules/homebridge-lg-thinq/src/devices/AirPurifier.ts:244:23)
    at AirPurifier.update (/var/lib/homebridge/node_modules/homebridge-lg-thinq/src/baseDevice.ts:33:10)
    at EventEmitter.emit (node:events:518:28)
    at /var/lib/homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:190:25
    at Array.forEach (<anonymous>)
    at /var/lib/homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:189:77

**Comment by nVuln** [comment]
got fixed it in `v1.8.8` please update
