### ISSUE TITLE
Current Relative Humidity': characteristic value expected valid finite number and received "NaN"

### ISSUE THREAD

**Issue by andredewaard** [nVuln/homebridge-lg-thinq#319]
**Describe The Bug:**
This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "NaN"

**To Reproduce:**
Add an LG AC

```
[11/27/2024, 3:25:39 PM] [LGThinQ] [Slaapkamer] Received snapshot:  {"airState.tempState.current":15,"meta":{"allDeviceInfoUpdate":false,"messageId":"HIs7R9OBQNOj8U-AWvrW_w"},"mid":3244237178,"online":true,"static":{"countryCode":"NL","deviceType":"401"},"timestamp":1732717539172}
[11/27/2024, 3:25:39 PM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[11/27/2024, 3:25:39 PM] [homebridge-lg-thinq] Error: 
    at CurrentRelativeHumidity.Characteristic.characteristicWarning (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3016:105)
    at CurrentRelativeHumidity.Characteristic.validateUserInput (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2908:14)
    at CurrentRelativeHumidity.Characteristic.updateValue (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2333:20)
    at HumiditySensor.Service.updateCharacteristic (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:804:35)
    at AirConditioner.updateAccessoryCharacteristic (/volume1/homebridge/node_modules/homebridge-lg-thinq/src/devices/AirConditioner.ts:341:34)
    at AirConditioner.update (/volume1/homebridge/node_modules/homebridge-lg-thinq/src/baseDevice.ts:33:10)
    at EventEmitter.emit (node:events:514:28)
    at /volume1/homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:198:23
    at DeviceClient.<anonymous> (/volume1/homebridge/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:291:9)
    at DeviceClient.emit (node:events:514:28)
[11/27/2024, 3:25:39 PM] [LGThinQ] mqtt message received: {"data":{"state":{"reported":{"airState.tempState.current":15,"meta":{"allDeviceInfoUpdate":false,"messageId":"HIs7R9OBQNOj8U-AWvrW_w"},"mid":3244237178,"online":true,"static":{"countryCode":"NL","deviceType":"401"},"timestamp":1732717539172}}},"deviceId":"","type":"monitoring"}
```

**Plugin Config:**

```
{
    "country": "NL",
    "language": "en-NL",
    "auth_mode": "token",
    "refresh_token": "",
    "username": "",
    "password": "",
    "platform": "LGThinQ",
    "devices": [
        {
            "id": "",
            "name": "Airco kinderkamer",
            "type": "AC",
            "ac_air_quality": true,
            "ac_mode": "BOTH",
            "ac_swing_mode": "BOTH",
            "ac_temperature_sensor": true,
            "ac_humidity_sensor": true,
            "ac_led_control": false,
            "ac_fan_control": false,
            "ac_energy_save": false,
            "ac_air_clean": false,
            "ac_temperature_unit": "C"
        },
        {
            "id": "",
            "name": "Airco slaapkamer",
            "type": "AC",
            "ac_air_quality": true,
            "ac_mode": "BOTH",
            "ac_swing_mode": "BOTH",
            "ac_temperature_sensor": true,
            "ac_humidity_sensor": true,
            "ac_led_control": false,
            "ac_fan_control": false,
            "ac_energy_save": false,
            "ac_air_clean": false,
            "ac_temperature_unit": "C"
        },
        {
            "id": "",
            "name": "Airco kantoor",
            "type": "AC",
            "ac_air_quality": true,
            "ac_mode": "BOTH",
            "ac_swing_mode": "BOTH",
            "ac_temperature_sensor": true,
            "ac_humidity_sensor": true,
            "ac_led_control": false,
            "ac_fan_control": false,
            "ac_energy_save": false,
            "ac_air_clean": false,
            "ac_temperature_unit": "C"
        }
    ],
    "thinq1": false,
    "refresh_interval": 60
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.8.9
* **Homebridge Version**: 1.8.5
* **Node.js Version**: 20.9.0
* **NPM Version**: 10.8.2
* **Operating System**: Docker

**Comment by andredewaard** [comment]
@nVuln Anything on why this happens?

**Comment by HassanAzzam** [comment]
Having the same issue
