### ISSUE TITLE
Not able to get Token

### ISSUE THREAD

**Issue by svandive** [nVuln/homebridge-lg-thinq#323]
**Describe The Bug:**
I have setup a new Ubuntu 24.10 machine and the only thing on it besides the OS is HomeBridge and the LG Thinq Plugin.  I download the Plugin, filled in the configuration form with my Username and Password, checked the box to have the username and password remembered, and then clicked to get the Token.  The spinner comes up and spins for a few seconds, and then I am presented with a red box in the bottom right hand corner of the screen that says:

Error
Login error. Cannot read
properties of undefined (reading 'data')

The real issue is I can't find any type of log to read or details to see what about the login is failing.  I have verified the login on the LG website and I have full access to my three (3) Mini-Split ACs from the ThinQ App on my iPhone. 

However I did figure out that there is a 'thinq' 'app' and I used that to login manually.  This is what I received as a response.

```
homebridge@homebridge2:/var/lib/homebridge $ thinq login 'HIDDEN-EMAIL' 'HIDDEN-PASSWORD' auth
Start login: username = HIDDEN-EMAIL , password = HIDDEN-PASSWORD , country = US , language = en-US
TypeError: Cannot read properties of undefined (reading 'data')
    at /var/lib/homebridge/node_modules/homebridge-lg-thinq/dist/lib/Auth.js:111:65
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Auth.loginStep2 (/var/lib/homebridge/node_modules/homebridge-lg-thinq/dist/lib/Auth.js:108:27)
    at async Command.<anonymous> (/var/lib/homebridge/node_modules/homebridge-lg-thinq/dist/cli.js:58:25)
```

**To Reproduce:**
Pretty much no matter what I do to try and obtain the token.

**Expected behavior:**
Recive the token and have the configuration show me the three (3) Mini-Split AC units I have on the network

**Logs:**

```
No place that I can fine is this token retrieval logged.
```

**Plugin Config:**

```
{
    "platform": "LGThinQ",
    "name": "LGThinQ"
}
```

**Screenshots:**
![LG-ThinQ-Error](https://github.com/user-attachments/assets/71ec8541-36ad-41a1-ac59-56c06f5ac012)

**Environment:**

* **Plugin Version**: 1.8.9
* **Homebridge Version**: 1.8.5
* **Node.js Version**: 22.11.0
* **NPM Version**: 10.9.0
* **Operating System**: Linux homebridge2 6.11.0-9-generic Ubuntu SMP PREEMPT_DYNAMIC Mon Oct 14 13:19:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
* * Home bridge is running natively on this machine (not in a container and the machine is not a VM)

**Comment by reedptaylor** [comment]
Getting the same thing on my end when i tried installing yesterday. Did some digging and it looks like one of the sites used in the login process has an expired SSL certificate.

**Comment by svandive** [comment]
Ahh dude, that sucks.

**Comment by tjthyne** [comment]
Same on bookworm (rPi 5 homebridge image)

**Comment by nVuln** [comment]
please try filled `username` & `password` and set `auth_mode` to `account` for login mode in plugin setting like this
```
{
    "username": "---- login email ----",
    "password": "---- login password ---",
    "country": "US",
    "language": "en-US",
    "thinq1": true,
    "platform": "LGThinQ",
    "auth_mode": "account",
    "refresh_interval": 60,
}
```

**Comment by ksawerykarwacki** [comment]
@nVuln Tested that on mine and stil have the same issue:

```
{
    "username": "<mail>",
    "password": "<password>",
    "country": "PL",
    "language": "pl",
    "thinq1": true,
    "platform": "LGThinQ",
    "auth_mode": "account",
    "refresh_interval": 60
}
```

**Comment by ksawerykarwacki** [comment]
@nVuln still the same issue:

```
{
    "username": "<mail>",
    "password": "<password>",
    "country": "PL",
    "language": "pl-PL",
    "thinq1": true,
    "platform": "LGThinQ",
    "auth_mode": "account",
    "refresh_interval": 60
}
```


```
[01/12/2024, 19:11:08] [LGThinQ] ThinQ API is not ready. please check configuration and try again.
[01/12/2024, 19:11:08] [LGThinQ] Cannot read properties of undefined (reading 'data')
```

**Comment by guilhermesimoncello** [comment]
Same problem here, waiting for an update.

**Comment by deepontech** [comment]
I’m having the same problem. 

Just wanted to let you know. Thanks for the awesome plugin!

**Comment by deryck13** [comment]
I just tried it and worked as expected. Thanks :D

**Comment by svandive** [comment]
I can confirm that I can call a refresh token now.  

However, I have a new issue now, I can't get the plugin to display in Fahrenheit.  I have confirmed the entry in the JSON config but still it's refusing to switch from Celsius to Fahrenheit.  Any thoughts??

**Comment by svandive** [comment]
This isn't on the home app, this is in the HomeBridge interface when viewing the Accessories.

**Comment by svandive** [comment]
So it turns out the problem was between the keyboard and the chair....  I hadn't configured HomeBridge for Fahrenheit.  My bad...  sorry.  Everything is working great now.  Thank You
