### ISSUE TITLE
Washer doesn’t work

### ISSUE THREAD

**Issue by niXta1** [nVuln/homebridge-lg-thinq#46]
**Describe Your Problem:**
Washer does not work. It shows up, but does not show on/off etc.

* LG acc
* Usr
* PW
* Country: SE
* Lang: sv-SE
* Refresh: 10s

ThinQ 1: Enabled

**Logs:**

10/08/2021, 15:13:09Lg Thinq Bridge starting
10/08/2021, 15:13:13Lg Thinq BridgeLoaded plugin 'homebridge-lg-thinq'
10/08/2021, 15:13:13Lg Thinq BridgeLoading 1 platforms...
10/08/2021, 15:13:13Lg Thinq BridgeLGThinQLoading accessory from cache: washing machine
10/08/2021, 15:13:13Lg Thinq BridgeBridge is running on port 51836.
10/08/2021, 15:13:19Lg Thinq BridgeWARNINGunhandled rejection: Error: 0002 - 전문오류

**Plugin Config:**
Only UI changes

**Screenshots:**

**Environment:**
rPi3B

* **Plugin Version**:
1.08

* **Homebridge Version**: 
HOOBS Latest

* **Node.js Version**: 
Latest HOOBS

* **NPM Version**: 

* **Operating System**: 
HOOBS

**Comment by nVuln** [comment]
`10/08/2021, 15:13:19Lg Thinq BridgeWARNINGunhandled rejection: Error: 0002 - 전문오류`
I never saw this error before, also I don't have washer running thinq1 to test at this time
please use `homebridge-config-ui-x` to see full detail of error, it's better

**Comment by Aekung** [comment]
I also have the problem with my LG Washer. Here is my error.

```
[11/08/2021, 20:29:59] [homebridge-lg-thinq] Found device:  {"deviceId":"7665bdc0-0e9f-11f5-baa4-203dbd8cd75f","deviceType":201,"modelName":"WPHT","subModelNm":null,"sensorType":null,"alias":"เครื่องซักผ้า","deviceCode":"LA02","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE2","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"alex-home","timezoneCode":"Asia/Bangkok","timezoneCodeAlias":"Asia/Bangkok","sdsGuide":"{\"deviceCode\":\"LA02\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"318849","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210811125202000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"2.8","modelJsonUri":"https://kic.lgthinq.com:46030/api/webContents/modelJSON?modelName=WPHT&countryCode=WW&contentsId=JS0911021801883542&authKey=thinq","appModuleVer":"3.63","appModuleUri":"https://objectcontent.lgthinq.com/27342417-7989-4cd5-a248-9b204c437c3d?hdnts=exp=1690080696~hmac=57e58b829363251d0615a494886d685f1148c1f74649cb04d9fd7a19ebd3484b","appRestartYn":"Y","appModuleSize":"9896643","langPackProductTypeVer":"82.7","langPackProductTypeUri":"https://objectcontent.lgthinq.com/a7c1467d-2ab7-44eb-848b-30eac6afa714?hdnts=exp=1691721026~hmac=dbed53d616c4f3996fa42987e83ba199b8cc5d75843852e76f940c0a00267655","langPackModelVer":"4.1","langPackModelUri":"https://kic.lgthinq.com:46030/api/webContents/moduleDownload?type=langPack/MP/WPHT/MP_WM_WPHT_LANG_WW-WW_VER_4.1_NUTS.json&fileName=MP_WM_WPHT_LANG_WW-WW_VER_4.1_NUTS&authKey=thinq","roomId":"162868638513116881","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"1.3","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:FL-S:24-U:600-P:GPLUS_BIGIN","cardType":"Small","cardControl":"Base"}
[11/08/2021, 20:30:00] [homebridge-lg-thinq] Device not connected:  7665bdc0-0e9f-11f5-baa4-203dbd8cd75f: เครื่องซักผ้า (WASHER WPHT)
```

For some reason, device is not connected but I'm sure that it's connected and I'm currently washing my clothes by using Thinq App. Washer/Dryer is connected to thinq app just fine.

Do you see any possible reason for this?

**Comment by Aekung** [comment]
PS. When I tried executing the command through Homekit, this is what returned.

```
[11/08/2021, 20:44:30] [homebridge-lg-thinq] NotConnectedError: 
    at /usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/request.ts:10:11
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at API.thinq1PostRequest (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:84:12)
    at ThinQ.thinq1DeviceControl (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:140:14)
    at Washer.setActive (/usr/local/lib/node_modules/homebridge-lg-thinq/src/v1/devices/Washer.ts:28:5)
[11/08/2021, 20:44:30] [homebridge-lg-thinq] Characteristic 'Active': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[11/08/2021, 20:44:30] [homebridge-lg-thinq] Error: 
    at Active.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Active.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1598:18)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I think the problem is because the device is reported not connect in Homekit for some reason.

**Comment by nVuln** [comment]
I found some problem in authentication and it's throw NotConnectedError, just fixed it in `v1.0.10`, please update and check

**Comment by Aekung** [comment]
> I found some problem in authentication and it's throw NotConnectedError, just fixed it in `v1.0.10`, please update and check

Thanks for the update and the reply. However, updating the plugin to v1.0.10 returns this error to me.

```
[11/08/2021, 23:52:25] [homebridge-lg-thinq] Found device:  {"deviceId":"7665bdc0-0e9f-11f5-baa4-203dbd8cd75f","deviceType":201,"modelName":"WPHT","subModelNm":null,"sensorType":null,"alias":"เครื่องซักผ้า","deviceCode":"LA02","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE2","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"alex-home","timezoneCode":"Asia/Bangkok","timezoneCodeAlias":"Asia/Bangkok","sdsGuide":"{\"deviceCode\":\"LA02\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"318849","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210811125202000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"2.8","modelJsonUri":"https://kic.lgthinq.com:46030/api/webContents/modelJSON?modelName=WPHT&countryCode=WW&contentsId=JS0911021801883542&authKey=thinq","appModuleVer":"3.63","appModuleUri":"https://objectcontent.lgthinq.com/27342417-7989-4cd5-a248-9b204c437c3d?hdnts=exp=1690080696~hmac=57e58b829363251d0615a494886d685f1148c1f74649cb04d9fd7a19ebd3484b","appRestartYn":"Y","appModuleSize":"9896643","langPackProductTypeVer":"82.7","langPackProductTypeUri":"https://objectcontent.lgthinq.com/1e150108-549f-4272-9506-2336af8ec81b?hdnts=exp=1691720722~hmac=6d9915bea12d721171afd43484b8906c6282dcafc279aee41b7740aa8085e7a2","langPackModelVer":"4.1","langPackModelUri":"https://kic.lgthinq.com:46030/api/webContents/moduleDownload?type=langPack/MP/WPHT/MP_WM_WPHT_LANG_WW-WW_VER_4.1_NUTS.json&fileName=MP_WM_WPHT_LANG_WW-WW_VER_4.1_NUTS&authKey=thinq","roomId":"162868638513116881","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"QC_Modem_1.2.80","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:FL-S:24-U:600-P:GPLUS_BIGIN","cardType":"Small","cardControl":"Base"}
(node:22014) UnhandledPromiseRejectionWarning: Error: 0002 - 전문오류
    at /usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:92:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at API.thinq1PostRequest (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:84:12)
    at API.getMonitorResult (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:128:12)
    at ThinQ.pollMonitor (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:110:18)
    at LGThinQHomebridgePlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-lg-thinq/src/platform.ts:100:34)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-lg-thinq/src/platform.ts:53:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22014) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22014) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nVuln** [comment]
try again with `v1.0.11` please

**Comment by Aekung** [comment]
> try again with `v1.0.11` please

Sorry for the late reply. I was already midnight in my area so I fell asleep.

By the way, updated and will find a chance to check it out whether it's now working. Will have to find some clothes to do laundry loll.

Will update you later.

Thanks.

**Comment by Aekung** [comment]
Hello,

I found a strange behavior here. The exposed faucet in Homekit was working with the run down time exactly as reported in ThinQ app but then it decided to stop at last 18 minutes for some reason. I waited until the time ran out both in Washer Display and ThinQ app and checked on Homekit again but the faucet still on. I waited hour later to see that the faucet in the Homekit was still on. I then pressed on faucet to turn it off and it kept spinning in updating status for hours. By the end, I decided to restart the 'Homebridge LG ThinQ', which I installed as a child bridge, for the faucet to finally reported as off.

I didn't capture the log this time since I was in a hurry in the morning. Just decided to report the activity to you first. On my next laundry, I will try to capture the log error for you if the problem is still persisted.

Thank you.

**Comment by Aekung** [comment]
By the way, I checked the device configuration file, are there any reason that you comment out the stateless switch (finisher status update)? It should be useful if I use the stateless switch to trigger the smart bulb to flash once when the washer is done washing.

Can I uncommenting the line and turn the stateless switch back on once again? 


PS.

What's the method of capturing the trigger that activates the finish state of the washer? Should I config anything in LG app, like the name of the machine, to make it work as a trigger?

**Comment by nVuln** [comment]
that feature still in develop, it's not working right now, if you can fix it please make a PR
the concept is check notification of lg app, when washer is done, a new notification will be created, just capture it and trigger button, right now I don't have time to test and fix it

**Comment by nVuln** [comment]
you can check this commit https://github.com/nVuln/homebridge-lg-thinq/commit/d6901bbbf165c915b4aebf1cdf0047af6dc4ab36
I don't know why it's not work, still don't have a chance to test

**Comment by nVuln** [comment]
@niXta1 did your washer worked in latest version ?
