### ISSUE TITLE
Unable to see Fridge

### ISSUE THREAD

**Issue by simplytoast1** [nVuln/homebridge-lg-thinq#55]
**Describe Your Problem:**

I am able to successfully log in and the plugin sees the device ID of my fridge but even though I have it in the configuration and see no errors in the logs (its even successfully polling) I don’t see the accessory in HB or HK

**Logs:**

```
No errors
```

**Plugin Config:**

```json
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.0.12
* **Homebridge Version**:  1.3.4
* **Node.js Version**:  v14.17.0
* **NPM Version**:   v6.14.13
* **Operating System**:  macOS

**Comment by nVuln** [comment]
please turn on homebridge debug mode and upload debug log

**Comment by simplytoast1** [comment]
Thank you for the recommendation.  It seems my refrigerator is Thinq1 which gets skipped.  So we can chalk that up to user error.

**Comment by nVuln** [comment]
refrigerator in thinq1 is supported at latest version, please upgrade and try again

**Comment by simplytoast1** [comment]
1.1.0?  If so, I got a Thinq1 error

**Comment by nVuln** [comment]
> 1.1.0? If so, I got a Thinq1 error

did you enable thinq1 support in plugin setting ?
please upload error log

**Comment by simplytoast1** [comment]
[8/24/2021, 9:20:12 AM] [LGThinQ] Found device:  {"deviceId":"REDACTED","deviceType":101,"modelName":"2REF11EID___2","subModelNm":"","sensorType":null,"alias":"REFRIGERATOR","deviceCode":"KI0102","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE1","pccModelYn":"Y","autoOrderYn":"N","drServiceYn":"N","ssid":"REDACTED","timezoneCode":"America/New_York","timezoneCodeAlias":"USA/New_York","sdsGuide":"{\"deviceCode\":\"KI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"334505","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"REDACTED","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"2.3","modelJsonUri":"https://aic.lgthinq.com:46030/api/webContents/modelJSON?modelName=2REF11EID___2&countryCode=WW&contentsId=WW21063007020405374276&authKey=thinq","appModuleVer":"303.20","appModuleUri":"https://objectcontent.lgthinq.com/564c4846-f80f-4865-9372-31160a1010ed?hdnts=exp=1684281366~hmac=a0802768ae20ee30aa6d9154e23878212b6f5a87aff505bb35aafd7d4d3f9561","appRestartYn":"Y","appModuleSize":"7337592","langPackProductTypeVer":"47.1","langPackProductTypeUri":"https://objectcontent.lgthinq.com/b1be3924-8903-4b25-a455-107fe68fd051?hdnts=exp=1692767282~hmac=1f46da92b16e2fdfb0d06a0f04c10f1ead458ea719ba869d7918671cca1ff9fc","langPackModelVer":"","langPackModelUri":"","roomId":"","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"QC_Modem_1.2.76","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:RFBFFD-M:3D-P:A_MAJESTY3","cardType":"Small","cardControl":"Base"}
(node:69474) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'NaN' in undefined
    at DeviceModel.enumName (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/DeviceModel.ts:148:16)
    at Object.loopupEnum (/usr/local/lib/node_modules/homebridge-lg-thinq/src/v1/helper.ts:68:22)
    at Object.RefState [as default] (/usr/local/lib/node_modules/homebridge-lg-thinq/src/v1/transforms/RefState.ts:13:19)
    at Function.transform (/usr/local/lib/node_modules/homebridge-lg-thinq/src/v1/helper.ts:42:40)
    at ThinQ.pollMonitor (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:146:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at LGThinQHomebridgePlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-lg-thinq/src/platform.ts:104:34)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-lg-thinq/src/platform.ts:57:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:69474) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:69474) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nVuln** [comment]
> https://pastebin.com/9cypw9g8

got it, I'll fix this error in next release
