### ISSUE TITLE
Current Temperature NaN

### ISSUE THREAD

**Issue by jpsak09** [nVuln/homebridge-lg-thinq#65]
**Describe The Bug:**
Temperature error in logs, not accurately displayed in HomeKit.

**To Reproduce:**
Happens consistently in my HomeBridge instance.

**Expected behavior:**
Accurate temperature information for refrigerator and freezer.

**Logs:**

[8/30/2021, 10:19:13 PM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[8/30/2021, 10:19:13 PM] [homebridge-lg-thinq] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at CurrentTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at Thermostat.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at Refrigerator.updateAccessoryCharacteristic (/homebridge/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:82:24)
    at EventEmitter.emit (events.js:400:28)
    at /homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:167:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Plugin Config:**

"username": "XXX",
            "password": "XXX",
            "country": "US",
            "language": "en-US",
            "thinq1": true,
            "washer_trigger": false,
            "platform": "LGThinQ",
            "auth_mode": "token",
            "refresh_token": "XXX",
            "devices": [
                {
                    "id": "XXX",
                    "name": "Refrigerator",
                    "type": "REFRIGERATOR",
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": false,
                    "ac_led_control": false,
                    "ac_fan_control": false
                }
            ],
            "refresh_interval": 15,

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-lg-thinq v1.1.2
* **Homebridge Version**: v1.3.4
* **Node.js Version**: v14.17.5
* **NPM Version**: v6.14.14
* **Operating System**: Docker

**Comment by nVuln** [comment]
please upload your homebridge debug log

**Comment by jpsak09** [comment]
Are there other logs that I should be providing other than what I added in the original post?

No, the temperature is not displayed correctly.  The icons look like they may be close/accurate though, my fridge is set to 34 degrees F and my freezer is set to -1 degrees F.  Attached are screenshots of what my homekit looks like.  Let me know what other information you'd like me to supply.

Also for some reason, every time I try to change the Hardware Display value for the accessory in homekit from Celsius to Fahrenheit, the setting never sticks/saves.  Not sure if that is a homekit bug/unrelated.

Screenshots: https://imgur.com/a/aJpPKeG

![IMG_1748](https://user-images.githubusercontent.com/6643192/131536389-bc8e0767-b48b-4241-beeb-6c4f63f8bf1e.PNG)
![IMG_1749](https://user-images.githubusercontent.com/6643192/131536393-5528756e-03fa-4bdd-9a3d-49e95a9cd972.PNG)
![IMG_1750](https://user-images.githubusercontent.com/6643192/131536396-dce7fb12-1fba-4d59-8631-b04ac9915467.PNG)

**Comment by jpsak09** [comment]
I tried to copy and paste what I think was related only to this plugin.  Let me know if I'm still missing anything or if I should omit any sensitive information from it (don't think I need to here).

[8/31/2021, 12:17:07 PM] Loaded 1 cached accessories from cachedAccessories.0ECC1A0495A7.
[8/31/2021, 12:17:07 PM] [homebridge-lg-thinq] Loading accessory from cache: Refrigerator
Preparing Advertiser for 'homebridge-lg-thinq EFA1' using bonjour-hap backend!
[8/31/2021, 12:17:07 PM] [homebridge-lg-thinq] Executed didFinishLaunching callback
Starting to advertise 'homebridge-lg-thinq EFA1' using bonjour-hap backend!
[8/31/2021, 12:17:07 PM] Homebridge v1.3.4 (homebridge-lg-thinq) is running on port 41758.
ERROR: sendUpdateStatus Error: [object Object] | Message: Request failed with status code 404 ##unsure if this is related to this plugin or not

[8/31/2021, 12:17:12 PM] [homebridge-lg-thinq] Found device:  {"deviceId":"71996fa0-84f5-11ea-8592-b4e62a5e1be4","deviceType":101,"modelName":"2REF11EIIFM__","subModelNm":null,"sensorType":null,"alias":"Refrigerator","deviceCode":"KI0102","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE1","pccModelYn":"Y","autoOrderYn":"N","drServiceYn":"N","ssid":"2 Adults 1 Router","timezoneCode":"America/New_York","timezoneCodeAlias":"USA/New_York","sdsGuide":"{\"deviceCode\":\"KI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"334505","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210529043046000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"1.6","modelJsonUri":"https://aic.lgthinq.com:46030/api/webContents/modelJSON?modelName=2REF11EIIFM__&countryCode=WW&contentsId=WW21063007130974362151&authKey=thinq","appModuleVer":"303.20","appModuleUri":"https://objectcontent.lgthinq.com/564c4846-f80f-4865-9372-31160a1010ed?hdnts=exp=1684281366~hmac=a0802768ae20ee30aa6d9154e23878212b6f5a87aff505bb35aafd7d4d3f9561","appRestartYn":"Y","appModuleSize":"7337592","langPackProductTypeVer":"47.1","langPackProductTypeUri":"https://objectcontent.lgthinq.com/b1be3924-8903-4b25-a455-107fe68fd051?hdnts=exp=1692767282~hmac=1f46da92b16e2fdfb0d06a0f04c10f1ead458ea719ba869d7918671cca1ff9fc","langPackModelVer":"","langPackModelUri":"","roomId":"162226273971725812","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"QC_Modem_1.2.80","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:RFBFFD-M:3D-P:A_MAJESTY1","cardType":"Small","cardControl":"Base"}
[8/31/2021, 12:17:13 PM] [homebridge-lg-thinq] Restoring existing accessory from cache: Refrigerator
[8/31/2021, 12:17:13 PM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Target Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[8/31/2021, 12:17:13 PM] [homebridge-lg-thinq] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at TargetTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at Thermostat.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at new Refrigerator (/homebridge/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:39:25)
    at new Refrigerator (/homebridge/node_modules/homebridge-lg-thinq/src/v1/devices/Refrigerator.ts:5:1)
    at LGThinQHomebridgePlatform.discoverDevices (/homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:116:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:53:7)
[8/31/2021, 12:17:13 PM] [homebridge-lg-thinq] START polling device data.

[8/31/2021, 12:17:29 PM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[8/31/2021, 12:17:29 PM] [homebridge-lg-thinq] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at CurrentTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at Thermostat.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at Refrigerator.updateAccessoryCharacteristic (/homebridge/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:82:24)
    at EventEmitter.emit (events.js:400:28)
    at /homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:167:25
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by nVuln** [comment]
please install version `v1.2.0-test.5` and try again

<img width="311" alt="Screen Shot 2021-08-08 at 6 44 40 PM" src="https://user-images.githubusercontent.com/54855446/128630936-6cbbc371-6d06-44a7-8a69-c71209744d0b.png">

**Comment by jpsak09** [comment]
Installed that version and no errors show up in my log anymore.  The icons images appear correct, but the values are off.
![IMG_1753](https://user-images.githubusercontent.com/6643192/131705881-16c0bf63-d1a1-4113-8402-e64160ee440d.jpeg)

**Comment by nVuln** [comment]
> Installed that version and no errors show up in my log anymore.  The icons images appear correct, but the values are off.
> 
> ![IMG_1753](https://user-images.githubusercontent.com/6643192/131705881-16c0bf63-d1a1-4113-8402-e64160ee440d.jpeg)
> 
> 

Did you mean Express Fridge status OFF is not correct?

**Comment by jpsak09** [comment]
No the Fridge cooling to 37 is not correct, and technically the Freezer cooling to -0 is not correct either.  My fridge is set to 34 (like the icon shows) and my freezer is set to -1 (like the icon shows).

**Comment by nVuln** [comment]
> No the Fridge cooling to 37 is not correct, and technically the Freezer cooling to -0 is not correct either. My fridge is set to 34 (like the icon shows) and my freezer is set to -1 (like the icon shows).

I'll fix this issue on next release
