### ISSUE TITLE
Cannot add washer

### ISSUE THREAD

**Issue by bereil** [nVuln/homebridge-lg-thinq#71]
**Describe The Bug:**
Adding a washer, error is written to the log. 

**To Reproduce:**
Add a washer. 

**Expected behavior:**

**Logs:**

```
9/5/2021, 10:55:36 PM] [LGThinQ] Adding new accessory: Washer
(node:482637) UnhandledPromiseRejectionWarning: TypeError: this.serviceWasherDryer.getCharacteristic(...).onSet is not a function
    at new WasherDryer (/homebridge/node_modules/homebridge-lg-thinq/src/devices/WasherDryer.ts:37:8)
    at LGThinQHomebridgePlatform.discoverDevices (/homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:125:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:53:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:482637) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:482637) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Plugin Config:**

```
{
    "country": "HU",
    "language": "hu-HU",
    "auth_mode": "token",
    "refresh_token": "MYTOKEN",
    "username": "",
    "password": "",
    "devices": [
        {
            "id": "MYDEVICEID",
            "name": "Washer",
            "type": "WASHER",
            "ac_mode": "BOTH",
            "ac_swing_mode": "BOTH",
            "ac_temperature_sensor": false,
            "ac_led_control": false,
            "ac_fan_control": false
        }
    ],
    "refresh_interval": 120,
    "thinq1": false,
    "platform": "LGThinQ"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-lg-thinq v1.1.3
* **Homebridge Version**: v1.2.5
* **Node.js Version**: v14.15.5
* **NPM Version**: v6.14.11
* **Operating System**: Docker

**Comment by nVuln** [comment]
please update homebridge to latest version, `v1.3.x`

**Comment by bereil** [comment]
Thanks, works!
