### ISSUE TITLE
Support for ThinQ1 Platform Type of Air Purifier

### ISSUE THREAD

**Issue by placebocoder** [nVuln/homebridge-lg-thinq#74]
**Which device do you want to add? Please describe:**

I would like to add support for **platformtype thinq1** of air purifier. _(model number is below)_

**Describe the solution you'd like:**

I would like to add the model like other air purifiers

**Device Data:**

```
[06/09/2021, 15:38:08] [LGThinQ] Found device:  {"deviceId":"d286fe90-7149-11d3-80f9-7440be39d655","deviceType":402,"modelName":"AIR_910604_WW","subModelNm":null,"sensorType":null,"alias":"공기청정기","deviceCode":"LI02","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"AIR_TYPE1","pccModelYn":"Y","autoOrderYn":"N","drServiceYn":"N","ssid":"pLacebo 2.4G","timezoneCode":"Asia/Seoul","timezoneCodeAlias":"Korea/Seoul","sdsGuide":"{\"deviceCode\":\"LI02\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"226081","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210830152035000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":-1,"roomDeviceOrder":1,"ownershipYn":"Y","modelJsonVer":"3.8","modelJsonUri":"https://kic.lgthinq.com:46030/api/webContents/modelJSON?modelName=modelJSON_401&countryCode=KR&contentsId=d286fe90-7149-11d3-80f9-7440be39d655&authKey=thinq","appModuleVer":"6.19","appModuleUri":"https://objectcontent.lgthinq.com/2c8e4434-45c9-43e1-bcc2-c6e8b417e1cf?hdnts=exp=1680772241~hmac=bf2952411448c6509bd02f1faf68c78d00628d7d5996d85650fbad7f71ba9f73","appRestartYn":"Y","appModuleSize":"13601540","langPackProductTypeVer":"27.69","langPackProductTypeUri":"https://objectcontent.lgthinq.com/941eb6db-848c-456d-879b-a382f6e74d14?hdnts=exp=1693461158~hmac=2b7696ecce6fa2b6b57e5e8a942bc43c9a72519143ae28a978bade7da260efa7","langPackModelVer":"","langPackModelUri":"","roomId":"163033762425461694","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"2.6.2_RTOS_3K","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"P:MD-T:G2-F:B","cardType":"Small","cardControl":"Base"}
[06/09/2021, 15:38:08] [LGThinQ] Device not supported: d286fe90-7149-11d3-80f9-7440be39d655: 공기청정기 (AIR_PURIFIER AIR_910604_WW)
```

**Comment by nVuln** [comment]
I published test version `v1.2.0-test.9` for this feature, please install and test it

**Comment by placebocoder** [comment]
@nVuln 
First of all, thanks for the update. 🙏
I am very happy that most of the functions are working. 

But I have one minus problem about air quality (grade) is 'Unknown'

![Screenshot of Safari (2021-09-06 9-45-03 PM)](https://user-images.githubusercontent.com/39292357/132219529-7c0691d2-4842-4884-825c-eebf233249f2.png)

For other similar sensors, air quality is displayed in several grades. (Excellent/Good/Fair/Inferior/Poor)

![Screenshot of Safari (2021-09-06 9-40-05 PM)](https://user-images.githubusercontent.com/39292357/132218971-1b9457f5-46a6-4a47-a6cc-22e4b366f985.png)

**Comment by placebocoder** [comment]
there was some log about `homebridge-lg-thinq`

I hope that help you
```
[06/09/2021, 21:51:45] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[06/09/2021, 21:51:45] [homebridge-lg-thinq] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at On.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1915:14)
    at On.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at Lightbulb.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at AirPurifier.updateAccessoryCharacteristic (/usr/local/lib/node_modules/homebridge-lg-thinq/src/devices/AirPurifier.ts:180:23)
    at EventEmitter.emit (events.js:400:28)
    at /usr/local/lib/node_modules/homebridge-lg-thinq/src/platform.ts:167:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[06/09/2021, 21:51:53] [Homebridge UI] [admin] Accessory layout changes saved.
[06/09/2021, 21:52:45] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Air Quality': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[06/09/2021, 21:52:45] [homebridge-lg-thinq] Error: 
    at AirQuality.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at AirQuality.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at AirQuality.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at AirQualitySensor.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at AirPurifier.updateAccessoryCharacteristic (/usr/local/lib/node_modules/homebridge-lg-thinq/src/devices/AirPurifier.ts:175:30)
    at EventEmitter.emit (events.js:400:28)
    at /usr/local/lib/node_modules/homebridge-lg-thinq/src/platform.ts:167:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[06/09/2021, 21:52:45] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[06/09/2021, 21:52:45] [homebridge-lg-thinq] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at On.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1915:14)
    at On.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at Lightbulb.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at AirPurifier.updateAccessoryCharacteristic (/usr/local/lib/node_modules/homebridge-lg-thinq/src/devices/AirPurifier.ts:180:23)
    at EventEmitter.emit (events.js:400:28)
    at /usr/local/lib/node_modules/homebridge-lg-thinq/src/platform.ts:167:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by nVuln** [comment]
> @nVuln
> First of all, thanks for the update. 🙏
> 
> After applying the test version, I did a simple test and found some problems
> 
> The power button doesn't work and air quality (grade) is 'Unknown'
> 
> ![Screenshot of Safari (2021-09-06 9-45-03 PM)](https://user-images.githubusercontent.com/39292357/132219529-7c0691d2-4842-4884-825c-eebf233249f2.png)

air quality is displayed on your native LG thinQ app ?
I found data for PM1, PM2 and PM10, but I don't know which data is air quality score, not sure thinq1 is support it

> For other similar sensors, air quality is displayed in several grades. (Excellent/Good/Fair/Inferior/Poor)
> 
> ![Screenshot of Safari (2021-09-06 9-40-05 PM)](https://user-images.githubusercontent.com/39292357/132218971-1b9457f5-46a6-4a47-a6cc-22e4b366f985.png)

what kind of this device?

**Comment by nVuln** [comment]
`v1.2.0-test.10` is published now, added turn on/off, control speed, swing, light (if available)
I mapped `TotalAirPolution` to `quality overall` also, hope this correct

**Comment by placebocoder** [comment]
After applying `v1.2.0-test.10` version, Air Quality Unknown issue is solved. 👍🏻

![Screenshot of Safari (2021-09-06 10-55-55 PM)](https://user-images.githubusercontent.com/39292357/132228652-a8919262-f1f7-4095-8ebc-7657a39f571a.png)

and I tried turn on/off, swing, light but nothing works and I got some error logs.

The meaning of the Korean sentence is 'is an unregistered model.'

```
[06/09/2021, 22:54:22] [LGThinQ] TokenError: 0011 - 등록되지 않은 모델입니다.
    at /usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:250:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at API.thinq1PostRequest (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:240:12)
    at ThinQ.thinq1DeviceControl (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:172:14)
    at AirPurifier.setLight (/usr/local/lib/node_modules/homebridge-lg-thinq/src/v1/devices/AirPurifier.ts:50:5)
```

**Comment by placebocoder** [comment]
> > @nVuln
> > First of all, thanks for the update. 🙏
> > After applying the test version, I did a simple test and found some problems
> > The power button doesn't work and air quality (grade) is 'Unknown'
> > ![Screenshot of Safari (2021-09-06 9-45-03 PM)](https://user-images.githubusercontent.com/39292357/132219529-7c0691d2-4842-4884-825c-eebf233249f2.png)
> 
> air quality is displayed on your native LG thinQ app ?
> I found data for PM1, PM2 and PM10, but I don't know which data is air quality score, not sure thinq1 is support it
> 
> > For other similar sensors, air quality is displayed in several grades. (Excellent/Good/Fair/Inferior/Poor)
> > ![Screenshot of Safari (2021-09-06 9-40-05 PM)](https://user-images.githubusercontent.com/39292357/132218971-1b9457f5-46a6-4a47-a6cc-22e4b366f985.png)
> 
> what kind of this device?

yes, air quality is displayed on LG thinQ app

![photo_2021-09-06_23-05-28](https://user-images.githubusercontent.com/39292357/132229267-0b60e6ba-d3b1-48cd-8f06-4c2c19ae5ebf.jpg)

also it's displayed  (ordered)
- total air quality (applied)
- pm2.5
- smell 
- power (?)
- swing fan power
- swing on/off
- air sterilization
- light
- schedule

**Comment by placebocoder** [comment]
I share a http response log of my thinq app I captured by proxy server on my phone. I would like to share it in case it helps.

```json
{
  "lgedmRoot": {
    "returnCd": "0000",
    "returnMsg": "OK",
    "workList": {
      "deviceId": "d286fe90-7149-11d3-80f9-7440be39d655",
      "deviceState": "E",
      "format": "B64",
      "returnCode": "0000",
      "returnData": "eyJPcGVyYXRpb24iOiIxIiwiT3BNb2RlIjoiMTMiLCJXaW5kU3RyZW5ndGgiOiI4IiwiVGVtcFVuaXQiOiJOUyIsIlRlbXBDdXIiOiI0MCIsIlRlbXBDZmciOiIwIiwiR3JvdXBUeXBlIjoiMTIiLCJTbGVlcFRpbWUiOiIwIiwiT25UaW1lIjoiMCIsIk9mZlRpbWUiOiIwIiwiUmFjQWRkRnVuYyI6Ik5TIiwiRXh0cmFPcCI6IjAiLCJEaWFnQ29kZSI6IjAwIiwiVGltZUJzT24iOiIwIiwiVGltZUJzT2ZmIjoiMCIsIkFpckNsZWFuIjoiMCIsIkF1dG9EcnkiOiIwIiwiUG93ZXJTYXZlIjoiMCIsIldEaXJWU3RlcCI6IjAiLCJXRGlySFN0ZXAiOiIwIiwiVGVtcExpbWl0TWF4IjoiMCIsIlRlbXBMaW1pdE1pbiI6IjAiLCJEdWN0Wm9uZVR5cGUiOiIwIiwiWm9uZUNvbnRyb2wiOiIwIiwiRFJFRCI6IjAiLCJTZW5zb3JQTTEiOiI4IiwiU2Vuc29yUE0yIjoiOCIsIlNlbnNvclBNMTAiOiIxMSIsIkFpclBvbHV0aW9uIjoiMSIsIkh1bWlkaXR5Q2ZnIjoiMCIsIldhdGVyVGVtcENvb2xNaW4iOiJOUyIsIldhdGVyVGVtcENvb2xNYXgiOiJOUyIsIldhdGVyVGVtcEhlYXRNaW4iOiJOUyIsIldhdGVyVGVtcEhlYXRNYXgiOiJOUyIsIkhvdFdhdGVyVGVtcE1pbiI6Ik5TIiwiSG90V2F0ZXJUZW1wTWF4IjoiTlMiLCJTZW5zb3JIdW1pZGl0eSI6IjMwIiwiVG90YWxBaXJQb2x1dGlvbiI6IjEiLCJTZW5zb3JNb24iOiIxIiwiQ2xlYW5EcnkiOiIwIiwiUHJvZHVjdFN0YXR1cyI6IjAiLCJBaXJNb25pdG9yaW5nIjoiMCIsIkh1bWlkaWZpY2F0aW9uIjoiMCIsIkFpckZhc3QiOiIwIiwiQWlyUmVtb3ZhbCI6IjAiLCJBaXJVVkRpc2luZmVjdGlvbiI6IjAiLCJXYXRlcnRhbmtMaWdodCI6IjAiLCJTaWduYWxMaWdodGluZyI6IjEiLCJXRGlyVXBEb3duIjoiMCIsIldEaXJMZWZ0UmlnaHQiOiIwIiwiV1N3aXJsIjoiMCIsIkpldCI6IjAiLCJMb3dIZWF0aW5nIjoiMCIsIkNpcmN1bGF0ZVN0cmVuZ3RoIjoiOCIsIkNpcmN1bGF0ZURpciI6IjEiLCJBbnRpQnVncyI6IjAiLCJJY2VWYWxsZXkiOiIwIiwiSHVtc2F2ZSI6IjAiLCJXYXRlclRlbXBDdXIiOiIwIiwiSG90V2F0ZXJUZW1wQ3VyIjoiMCIsIkhvdFdhdGVyVGVtcENmZyI6IjAiLCJIb3RXYXRlck1vZGUiOiIwIiwiSG90V2F0ZXIiOiIwIiwiQVdIUFRlbXBDZmdTd2l0Y2giOiIwIiwiQWlyVGVtcENvb2xNaW4iOiJOUyIsIkFpclRlbXBDb29sTWF4IjoiTlMiLCJBaXJUZW1wSGVhdE1pbiI6Ik5TIiwiQWlyVGVtcEhlYXRNYXgiOiJOUyIsIldhdGVySW5UZW1wQ3VyIjoiMCIsIkFXSFBXQVRlbXBDb250cm9sU3RhIjoiMCIsIkRpc3BsYXlDb250cm9sIjoiMCIsIlNtYXJ0Q2FyZSI6IjAiLCJUd29TZXRDb29sVGVtcCI6IjAiLCJUd29TZXRIZWF0VGVtcCI6IjAiLCJUd29TZXRDb29sVVNMIjoiMCIsIlR3b1NldENvb2xMU0wiOiIwIiwiVHdvU2V0SGVhdFVTTCI6IjAiLCJUd29TZXRIZWF0TFNMIjoiMCIsIlR3b1NldEFDT1N0YXRlIjoiMCIsIlR3b1NldE1vZGVEZWFkYmFuZCI6IjAiLCJUd29TZXRTdGF0ZSI6IjAifQ==",
      "stateCode": "S",
      "workId": "n-d286fe90-7149-11d3-80f9-7440be39d655"
    }
  }
}
```

**Comment by nVuln** [comment]
please try `v1.2.0-test.11` and see if `turn on/off, swing, light` is worked

**Comment by nVuln** [comment]
> I share a http response log of my thinq app I captured by proxy server on my phone. I would like to share it in case it helps.
> 
> ```json
> {
>   "lgedmRoot": {
>     "returnCd": "0000",
>     "returnMsg": "OK",
>     "workList": {
>       "deviceId": "d286fe90-7149-11d3-80f9-7440be39d655",
>       "deviceState": "E",
>       "format": "B64",
>       "returnCode": "0000",
>       "returnData": "eyJPcGVyYXRpb24iOiIxIiwiT3BNb2RlIjoiMTMiLCJXaW5kU3RyZW5ndGgiOiI4IiwiVGVtcFVuaXQiOiJOUyIsIlRlbXBDdXIiOiI0MCIsIlRlbXBDZmciOiIwIiwiR3JvdXBUeXBlIjoiMTIiLCJTbGVlcFRpbWUiOiIwIiwiT25UaW1lIjoiMCIsIk9mZlRpbWUiOiIwIiwiUmFjQWRkRnVuYyI6Ik5TIiwiRXh0cmFPcCI6IjAiLCJEaWFnQ29kZSI6IjAwIiwiVGltZUJzT24iOiIwIiwiVGltZUJzT2ZmIjoiMCIsIkFpckNsZWFuIjoiMCIsIkF1dG9EcnkiOiIwIiwiUG93ZXJTYXZlIjoiMCIsIldEaXJWU3RlcCI6IjAiLCJXRGlySFN0ZXAiOiIwIiwiVGVtcExpbWl0TWF4IjoiMCIsIlRlbXBMaW1pdE1pbiI6IjAiLCJEdWN0Wm9uZVR5cGUiOiIwIiwiWm9uZUNvbnRyb2wiOiIwIiwiRFJFRCI6IjAiLCJTZW5zb3JQTTEiOiI4IiwiU2Vuc29yUE0yIjoiOCIsIlNlbnNvclBNMTAiOiIxMSIsIkFpclBvbHV0aW9uIjoiMSIsIkh1bWlkaXR5Q2ZnIjoiMCIsIldhdGVyVGVtcENvb2xNaW4iOiJOUyIsIldhdGVyVGVtcENvb2xNYXgiOiJOUyIsIldhdGVyVGVtcEhlYXRNaW4iOiJOUyIsIldhdGVyVGVtcEhlYXRNYXgiOiJOUyIsIkhvdFdhdGVyVGVtcE1pbiI6Ik5TIiwiSG90V2F0ZXJUZW1wTWF4IjoiTlMiLCJTZW5zb3JIdW1pZGl0eSI6IjMwIiwiVG90YWxBaXJQb2x1dGlvbiI6IjEiLCJTZW5zb3JNb24iOiIxIiwiQ2xlYW5EcnkiOiIwIiwiUHJvZHVjdFN0YXR1cyI6IjAiLCJBaXJNb25pdG9yaW5nIjoiMCIsIkh1bWlkaWZpY2F0aW9uIjoiMCIsIkFpckZhc3QiOiIwIiwiQWlyUmVtb3ZhbCI6IjAiLCJBaXJVVkRpc2luZmVjdGlvbiI6IjAiLCJXYXRlcnRhbmtMaWdodCI6IjAiLCJTaWduYWxMaWdodGluZyI6IjEiLCJXRGlyVXBEb3duIjoiMCIsIldEaXJMZWZ0UmlnaHQiOiIwIiwiV1N3aXJsIjoiMCIsIkpldCI6IjAiLCJMb3dIZWF0aW5nIjoiMCIsIkNpcmN1bGF0ZVN0cmVuZ3RoIjoiOCIsIkNpcmN1bGF0ZURpciI6IjEiLCJBbnRpQnVncyI6IjAiLCJJY2VWYWxsZXkiOiIwIiwiSHVtc2F2ZSI6IjAiLCJXYXRlclRlbXBDdXIiOiIwIiwiSG90V2F0ZXJUZW1wQ3VyIjoiMCIsIkhvdFdhdGVyVGVtcENmZyI6IjAiLCJIb3RXYXRlck1vZGUiOiIwIiwiSG90V2F0ZXIiOiIwIiwiQVdIUFRlbXBDZmdTd2l0Y2giOiIwIiwiQWlyVGVtcENvb2xNaW4iOiJOUyIsIkFpclRlbXBDb29sTWF4IjoiTlMiLCJBaXJUZW1wSGVhdE1pbiI6Ik5TIiwiQWlyVGVtcEhlYXRNYXgiOiJOUyIsIldhdGVySW5UZW1wQ3VyIjoiMCIsIkFXSFBXQVRlbXBDb250cm9sU3RhIjoiMCIsIkRpc3BsYXlDb250cm9sIjoiMCIsIlNtYXJ0Q2FyZSI6IjAiLCJUd29TZXRDb29sVGVtcCI6IjAiLCJUd29TZXRIZWF0VGVtcCI6IjAiLCJUd29TZXRDb29sVVNMIjoiMCIsIlR3b1NldENvb2xMU0wiOiIwIiwiVHdvU2V0SGVhdFVTTCI6IjAiLCJUd29TZXRIZWF0TFNMIjoiMCIsIlR3b1NldEFDT1N0YXRlIjoiMCIsIlR3b1NldE1vZGVEZWFkYmFuZCI6IjAiLCJUd29TZXRTdGF0ZSI6IjAifQ==",
>       "stateCode": "S",
>       "workId": "n-d286fe90-7149-11d3-80f9-7440be39d655"
>     }
>   }
> }
> ```

what is current state of your device ?
I decoded your device data and saw OpMode = 13 mean @AP_MAIN_MID_OPMODE_CIRCULATOR_CLEAN_W

**Comment by placebocoder** [comment]
> please try `v1.2.0-test.11` and see if `turn on/off, swing, light` is worked

all is working well. 



> > I share a http response log of my thinq app I captured by proxy server on my phone. I would like to share it in case it helps.
> > ```json
> > {
> >   "lgedmRoot": {
> >     "returnCd": "0000",
> >     "returnMsg": "OK",
> >     "workList": {
> >       "deviceId": "d286fe90-7149-11d3-80f9-7440be39d655",
> >       "deviceState": "E",
> >       "format": "B64",
> >       "returnCode": "0000",
> >       "returnData": "eyJPcGVyYXRpb24iOiIxIiwiT3BNb2RlIjoiMTMiLCJXaW5kU3RyZW5ndGgiOiI4IiwiVGVtcFVuaXQiOiJOUyIsIlRlbXBDdXIiOiI0MCIsIlRlbXBDZmciOiIwIiwiR3JvdXBUeXBlIjoiMTIiLCJTbGVlcFRpbWUiOiIwIiwiT25UaW1lIjoiMCIsIk9mZlRpbWUiOiIwIiwiUmFjQWRkRnVuYyI6Ik5TIiwiRXh0cmFPcCI6IjAiLCJEaWFnQ29kZSI6IjAwIiwiVGltZUJzT24iOiIwIiwiVGltZUJzT2ZmIjoiMCIsIkFpckNsZWFuIjoiMCIsIkF1dG9EcnkiOiIwIiwiUG93ZXJTYXZlIjoiMCIsIldEaXJWU3RlcCI6IjAiLCJXRGlySFN0ZXAiOiIwIiwiVGVtcExpbWl0TWF4IjoiMCIsIlRlbXBMaW1pdE1pbiI6IjAiLCJEdWN0Wm9uZVR5cGUiOiIwIiwiWm9uZUNvbnRyb2wiOiIwIiwiRFJFRCI6IjAiLCJTZW5zb3JQTTEiOiI4IiwiU2Vuc29yUE0yIjoiOCIsIlNlbnNvclBNMTAiOiIxMSIsIkFpclBvbHV0aW9uIjoiMSIsIkh1bWlkaXR5Q2ZnIjoiMCIsIldhdGVyVGVtcENvb2xNaW4iOiJOUyIsIldhdGVyVGVtcENvb2xNYXgiOiJOUyIsIldhdGVyVGVtcEhlYXRNaW4iOiJOUyIsIldhdGVyVGVtcEhlYXRNYXgiOiJOUyIsIkhvdFdhdGVyVGVtcE1pbiI6Ik5TIiwiSG90V2F0ZXJUZW1wTWF4IjoiTlMiLCJTZW5zb3JIdW1pZGl0eSI6IjMwIiwiVG90YWxBaXJQb2x1dGlvbiI6IjEiLCJTZW5zb3JNb24iOiIxIiwiQ2xlYW5EcnkiOiIwIiwiUHJvZHVjdFN0YXR1cyI6IjAiLCJBaXJNb25pdG9yaW5nIjoiMCIsIkh1bWlkaWZpY2F0aW9uIjoiMCIsIkFpckZhc3QiOiIwIiwiQWlyUmVtb3ZhbCI6IjAiLCJBaXJVVkRpc2luZmVjdGlvbiI6IjAiLCJXYXRlcnRhbmtMaWdodCI6IjAiLCJTaWduYWxMaWdodGluZyI6IjEiLCJXRGlyVXBEb3duIjoiMCIsIldEaXJMZWZ0UmlnaHQiOiIwIiwiV1N3aXJsIjoiMCIsIkpldCI6IjAiLCJMb3dIZWF0aW5nIjoiMCIsIkNpcmN1bGF0ZVN0cmVuZ3RoIjoiOCIsIkNpcmN1bGF0ZURpciI6IjEiLCJBbnRpQnVncyI6IjAiLCJJY2VWYWxsZXkiOiIwIiwiSHVtc2F2ZSI6IjAiLCJXYXRlclRlbXBDdXIiOiIwIiwiSG90V2F0ZXJUZW1wQ3VyIjoiMCIsIkhvdFdhdGVyVGVtcENmZyI6IjAiLCJIb3RXYXRlck1vZGUiOiIwIiwiSG90V2F0ZXIiOiIwIiwiQVdIUFRlbXBDZmdTd2l0Y2giOiIwIiwiQWlyVGVtcENvb2xNaW4iOiJOUyIsIkFpclRlbXBDb29sTWF4IjoiTlMiLCJBaXJUZW1wSGVhdE1pbiI6Ik5TIiwiQWlyVGVtcEhlYXRNYXgiOiJOUyIsIldhdGVySW5UZW1wQ3VyIjoiMCIsIkFXSFBXQVRlbXBDb250cm9sU3RhIjoiMCIsIkRpc3BsYXlDb250cm9sIjoiMCIsIlNtYXJ0Q2FyZSI6IjAiLCJUd29TZXRDb29sVGVtcCI6IjAiLCJUd29TZXRIZWF0VGVtcCI6IjAiLCJUd29TZXRDb29sVVNMIjoiMCIsIlR3b1NldENvb2xMU0wiOiIwIiwiVHdvU2V0SGVhdFVTTCI6IjAiLCJUd29TZXRIZWF0TFNMIjoiMCIsIlR3b1NldEFDT1N0YXRlIjoiMCIsIlR3b1NldE1vZGVEZWFkYmFuZCI6IjAiLCJUd29TZXRTdGF0ZSI6IjAifQ==",
> >       "stateCode": "S",
> >       "workId": "n-d286fe90-7149-11d3-80f9-7440be39d655"
> >     }
> >   }
> > }
> > ```
> 
> what is current state of your device ?
> I decoded your device data and saw OpMode = 13 mean @AP_MAIN_MID_OPMODE_CIRCULATOR_CLEAN_W

now my air purifier mod is... maybe `clean booster`. The other modes are `single clean`, `dual clean`,  `auto`

![photo_2021-09-06_23-36-27](https://user-images.githubusercontent.com/39292357/132233061-5b968a26-a81f-4d35-ac43-22d72bd2912e.jpg)

I don't know if you know, but the image below is my model.

![medium03](https://user-images.githubusercontent.com/39292357/132233436-a6b95169-d174-48f5-be37-8e4f968ab2a1.jpg)

**Comment by nVuln** [comment]
> I don't know if you know, but the image below is my model.

yup, I have Air purifier too, but mini version, half size of your model 😆
currently, homekit do not support specified mode `clean booster` `single clean` or `dual clean`, only AUTO or MANUAL, hope they will added more soon

please double check if everything worked fine, let me know if you got any error

**Comment by placebocoder** [comment]
Since installing the last test version, everything has been working fine so far.

If there are any unusual logs or problems, I will write a comment again.

Thank you very much for your kind comments and very quick updates.
