### ISSUE TITLE
'Target Temperature': characteristic was supplied illegal value: number 0.6 exceeded minimum of 1.

### ISSUE THREAD

**Issue by jpsak09** [nVuln/homebridge-lg-thinq#86]
**Describe The Bug:**
The error message is displayed in my logs every 15 seconds (polling time).  The target temperature for both my freezer and refrigerator do not display correctly in the home app.

**To Reproduce:**
Reproducible every time.

**Expected behavior:**
Target temperatures to display the correct temperature.

**Logs:**

[9/21/2021, 9:31:23 AM] Registering platform 'homebridge-lg-thinq.LGThinQ'
[9/21/2021, 9:31:23 AM] [homebridge-lg-thinq] Loaded homebridge-lg-thinq v1.2.6 child bridge successfully
[9/21/2021, 9:31:24 AM] [homebridge-lg-thinq] Loading accessory from Homebridge cache: Refrigerator
Preparing Advertiser for 'homebridge-lg-thinq EFA1' using bonjour-hap backend!
[9/21/2021, 9:31:24 AM] [homebridge-lg-thinq] Executed didFinishLaunching callback
Starting to advertise 'homebridge-lg-thinq EFA1' using bonjour-hap backend!
[9/21/2021, 9:31:24 AM] Homebridge v1.3.4 (homebridge-lg-thinq) is running on port 41758.
[9/21/2021, 9:31:25 AM] [homebridge-lg-thinq] [request] get https://route.lgthinq.com:46030/v1/service/application/gateway-uri
[9/21/2021, 9:31:27 AM] [homebridge-lg-thinq] [request] post https://kic.lgthinq.com:46030/api/common/gatewayUriList
[9/21/2021, 9:31:30 AM] [homebridge-lg-thinq] [request] post https://us.lgeapi.com/oauth2/token
[9/21/2021, 9:31:31 AM] [homebridge-lg-thinq] [request] post https://aic.lgthinq.com:46030/api/member/login
[9/21/2021, 9:31:32 AM] [homebridge-lg-thinq] [request] get https://us.lgeapi.com/users/profile
[9/21/2021, 9:31:32 AM] [homebridge-lg-thinq] Successfully connected to the ThinQ API.
[9/21/2021, 9:31:32 AM] [homebridge-lg-thinq] [request] get https://aic-service.lgthinq.com:46030/v1/service/homes
[9/21/2021, 9:31:34 AM] [homebridge-lg-thinq] [request] get https://aic-service.lgthinq.com:46030/v1/service/homes/162226205558192254
[9/21/2021, 9:31:34 AM] [homebridge-lg-thinq] Device data:  {"deviceId":"71996fa0-84f5-11ea-8592-b4e62a5e1be4","deviceType":101,"modelName":"2REF11EIIFM__","subModelNm":null,"sensorType":null,"alias":"Refrigerator","deviceCode":"KI0102","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE1","pccModelYn":"Y","autoOrderYn":"N","drServiceYn":"N","ssid":"2 Adults 1 Router","timezoneCode":"America/New_York","timezoneCodeAlias":"USA/New_York","sdsGuide":"{\"deviceCode\":\"KI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"334505","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210529043046000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"1.6","modelJsonUri":"https://aic.lgthinq.com:46030/api/webContents/modelJSON?modelName=2REF11EIIFM__&countryCode=WW&contentsId=WW21063007130974362151&authKey=thinq","appModuleVer":"303.28","appModuleUri":"https://objectcontent.lgthinq.com/418261f4-75d9-4653-a35b-b4025ab832e3?hdnts=exp=1690365986~hmac=52d3ea014f0bcba1c7c7d0591cae3111d3e29114cfee92b7c1058ea0f6c34844","appRestartYn":"Y","appModuleSize":"8319339","langPackProductTypeVer":"47.5","langPackProductTypeUri":"https://objectcontent.lgthinq.com/92f6f006-c100-4957-a349-345b1acbb48d?hdnts=exp=1694771376~hmac=7a80fee9757948997d1a38cf50c5b7c9215b683bb225fb1e5545625499c5210b","langPackModelVer":"","langPackModelUri":"","roomId":"162226273971725812","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"QC_Modem_1.2.80","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:RFBFFD-M:3D-P:A_MAJESTY1","cardType":"Small","cardControl":"Base"}
[9/21/2021, 9:31:34 AM] [homebridge-lg-thinq] [Refrigerator] Setting up device!
[9/21/2021, 9:31:34 AM] [homebridge-lg-thinq] [request] post https://aic.lgthinq.com:46030/api/rti/rtiMon
[9/21/2021, 9:31:34 AM] [homebridge-lg-thinq] Restoring existing accessory: 71996fa0-84f5-11ea-8592-b4e62a5e1be4: Refrigerator (REFRIGERATOR 2REF11EIIFM__)
[9/21/2021, 9:31:34 AM] [homebridge-lg-thinq] Start polling device data every 15 second.
[9/21/2021, 9:31:50 AM] [homebridge-lg-thinq] [request] post https://aic.lgthinq.com:46030/api/rti/rtiResult
[9/21/2021, 9:31:50 AM] [homebridge-lg-thinq] [Refrigerator] Received snapshot:  {"refState":{"fridgeTemp":14,"freezerTemp":9,"atLeastOneDoorOpen":"CLOSE","tempUnit":"FAHRENHEIT","expressMode":"1"},"online":true,"raw":{"TempRefrigerator":"14","TempFreezer":"9","IcePlus":"1","FreshAirFilter":"2","SmartSavingMode":"0","WaterFilterUsedMonth":"5","DoorOpenState":"0","TempUnit":"0"}}
[9/21/2021, 9:31:50 AM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 0.6 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[9/21/2021, 9:31:50 AM] [homebridge-lg-thinq] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1946:16)
    at TargetTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at Thermostat.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at Refrigerator.updateAccessoryCharacteristic (/homebridge/node_modules/homebridge-lg-thinq/src/devices/Refrigerator.ts:110:26)
    at Refrigerator.update (/homebridge/node_modules/homebridge-lg-thinq/src/baseDevice.ts:33:10)
    at EventEmitter.emit (events.js:400:28)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:224:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Plugin Config:**

{
            "username": "XXX",
            "password": "XXX",
            "country": "US",
            "language": "en-US",
            "thinq1": true,
            "washer_trigger": false,
            "platform": "LGThinQ",
            "auth_mode": "token",
            "refresh_token": "XXX",
            "devices": [
                {
                    "id": "71996fa0-84f5-11ea-8592-b4e62a5e1be4",
                    "name": "Refrigerator",
                    "type": "REFRIGERATOR",
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": false,
                    "ac_led_control": false,
                    "ac_fan_control": false
                }
            ],
            "refresh_interval": 15,
            "_bridge": {
                "username": "XXX",
                "port": 41758
            }
        }

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-lg-thinq v1.2.6
* **Homebridge Version**: v1.3.4
* **Node.js Version**: v14.17.6
* **NPM Version**: v6.14.15
* **Operating System**: Docker

**Comment by nVuln** [comment]
I already published test version `v1.2.7-test.1` to fix this error, can you try it ?

**Comment by jpsak09** [comment]
Yep that worked. I'll use that version until the next release, thanks!
