### ISSUE TITLE
Errors with MQTT in logs

### ISSUE THREAD

**Issue by iShift** [nVuln/homebridge-lg-thinq#90]
Hi i get every some time that error in logs:

```
[10/13/2021, 7:17:57 PM] [LGThinQ] mqtt err: Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:375:28)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
[10/13/2021, 7:17:57 PM] [LGThinQ] MQTT disconnected, retrying in 60 seconds!
[10/13/2021, 7:17:58 PM] [LGThinQ] mqtt err: Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:375:28)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
```

... but everything works normally

**Comment by nVuln** [comment]
which country of your account ?

**Comment by iShift** [comment]
Thank you, now everything is ok! 
`[10/14/2021, 5:48:52 PM] [LGThinQ] Successfully connected to the MQTT server.`
