### ISSUE TITLE
Error: Cannot read property 'lgedmRoot' of undefined

### ISSUE THREAD

**Issue by mrfletch** [nVuln/homebridge-lg-thinq#97]
**Describe The Bug:**
Unable to view or control ThinQ1 air conditioner within Homekit. I have 3 air conditioners:
1. Office Air
2. Bedroom Air
3. Living Room Air

All 3 are the same model number: LG LP1417WSRSM

They're connected to WIFI and accessible/controllable from within the LG ThingQ app.

**To Reproduce:**
1. Install LG Thinq Plugin v1.2.9
2. Click the "Configuration" button
3. Click LG Account
4. Type username
5. Type password
6. Check ThinQ1 Support checkbox
7. Click Save
8. Reboot Hoobs
9. Above logs are generated

**Expected behavior:**
The Lg Thinq Bridge was connected to HomeKit. I expected to see the 3 air conditioners appear within the UI.

**Logs:**

```
10/30/2021, 2:17:44 AMLg Thinq Bridge starting
10/30/2021, 2:17:54 AMLg Thinq BridgeLoaded plugin 'homebridge-lg-thinq'
10/30/2021, 2:17:54 AMLg Thinq BridgeLoading 1 platforms...
10/30/2021, 2:17:54 AMLg Thinq BridgeBridge is running on port 51856.
10/30/2021, 2:18:14 AMLg Thinq BridgeLGThinQSuccessfully connected to the ThinQ API.
10/30/2021, 2:18:15 AMLg Thinq BridgeLGThinQ[Office Air] Setting up device!
10/30/2021, 2:18:19 AMLg Thinq BridgeLGThinQERRORCannot read property 'lgedmRoot' of undefined
```

**Plugin Config:**

```
{
    "platform": "LGThinQ",
    "country": "US",
    "language": "en-US",
    "refresh_interval": 60,
    "auth_mode": "account",
    "username": "[EMAIL ADDRESS HERE]",
    "password": "[PASSWORD HERE]",
    "thinq1": true
}
```

**Screenshots:**
None

**Environment:**

* **Plugin Version**: 1.2.9
* **Homebridge Version**: 1.3.5
* **Node.js Version**: 14.18.1
* **NPM Version**: 6.14.15
* **Operating System**: Hoobs All-in-one-box

**Comment by nVuln** [comment]
can you enable homebridge debug mode and try restart it ?

**Comment by mrfletch** [comment]
Does this help?

```
10/30/2021, 4:18:59 PMLg Thinq BridgeInitializing HAP-NodeJS v0.9.6...
10/30/2021, 4:18:59 PMLg Thinq BridgeRegistering platform 'homebridge-lg-thinq.LGThinQ'
10/30/2021, 4:18:59 PMLg Thinq BridgePreparing Advertiser for 'Lg Thinq Bridge F366' using bonjour-hap backend!
10/30/2021, 4:18:59 PMLg Thinq BridgeStarting to advertise 'Lg Thinq Bridge F366' using bonjour-hap backend!
10/30/2021, 4:18:38 PMLg Thinq BridgeLoaded plugin 'homebridge-lg-thinq'
10/30/2021, 4:18:38 PMLg Thinq BridgeLoading 1 platforms...
10/30/2021, 4:18:38 PMLg Thinq BridgeBridge is running on port 51856.
10/30/2021, 4:18:45 PMLg Thinq BridgeLGThinQSuccessfully connected to the ThinQ API.
10/30/2021, 4:18:47 PMLg Thinq BridgeLGThinQ[Office Air] Setting up device!
10/30/2021, 4:18:51 PMLg Thinq BridgeLGThinQERRORCannot read property 'lgedmRoot' of undefined
10/30/2021, 4:19:49 PMLg Thinq BridgeWARNINGunhandled rejection: SyntaxError: Unexpected token u in JSON at position 0
10/30/2021, 4:21:50 PMLg Thinq BridgeInitializing HAP-NodeJS v0.9.6...
10/30/2021, 4:21:55 PMLg Thinq BridgeLoaded plugin 'homebridge-lg-thinq'
10/30/2021, 4:21:55 PMLg Thinq BridgeRegistering platform 'homebridge-lg-thinq.LGThinQ'
10/30/2021, 4:21:55 PMLg Thinq BridgeLoading 1 platforms...
10/30/2021, 4:21:55 PMLg Thinq BridgeLGThinQExecuted didFinishLaunching callback
10/30/2021, 4:21:55 PMLg Thinq BridgePreparing Advertiser for 'Lg Thinq Bridge F366' using bonjour-hap backend!
10/30/2021, 4:21:55 PMLg Thinq BridgeSetup URI 'X-HM://0023ISYWY3C4T'
10/30/2021, 4:21:55 PMLg Thinq BridgeStarting to advertise 'Lg Thinq Bridge F366' using bonjour-hap backend!
10/30/2021, 4:21:55 PMLg Thinq BridgeBridge is running on port 51856.
10/30/2021, 4:21:56 PMLg Thinq BridgeLGThinQ[request] get https://route.lgthinq.com:46030/v1/service/application/gateway-uri
10/30/2021, 4:21:59 PMLg Thinq BridgeLGThinQ[request] post https://us.m.lgaccount.com/spx/preLogin
10/30/2021, 4:22:00 PMLg Thinq BridgeLGThinQ[request] post https://us.emp.lgsmartplatform.com/emp/v2.0/account/session/mrfletch%40mac.com
10/30/2021, 4:22:00 PMLg Thinq BridgeLGThinQ[request] get https://us.m.lgaccount.com/spx/searchKey?key_name=OAUTH_SECRETKEY&sever_type=OP
10/30/2021, 4:22:01 PMLg Thinq BridgeLGThinQ[request] post https://emp-oauth.lgecloud.com/emp/oauth2/token/empsession
10/30/2021, 4:22:01 PMLg Thinq BridgeLGThinQ[request] get https://us.lgeapi.com/users/profile
10/30/2021, 4:22:01 PMLg Thinq BridgeLGThinQSuccessfully connected to the ThinQ API.
10/30/2021, 4:22:01 PMLg Thinq BridgeLGThinQ[request] get https://aic-service.lgthinq.com:46030/v1/service/homes
10/30/2021, 4:22:03 PMLg Thinq BridgeLGThinQ[request] get https://aic-service.lgthinq.com:46030/v1/service/homes/160066146046097594
10/30/2021, 4:22:03 PMLg Thinq BridgeLGThinQDevice data:  {"deviceId":"d27af0a0-7149-11d3-80aa-a06faaeb886c","deviceType":401,"modelName":"POT_056905_WW","subModelNm":null,"sensorType":null,"alias":"Office Air","deviceCode":"AI01","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"POT_TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"Orion","timezoneCode":"America/New_York","timezoneCodeAlias":"USA/New_York","sdsGuide":"{\"deviceCode\":\"AI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"334505","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210306194202000","regIndex":0,"blackboxYn":null,"groupableYn":"Y","controllableYn":"Y","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"10.55","modelJsonUri":"https://aic.lgthinq.com:46030/api/webContents/modelJSON?modelName=modelJSON_401&countryCode=KR&contentsId=d27af0a0-7149-11d3-80aa-a06faaeb886c&authKey=thinq","appModuleVer":"17.23","appModuleUri":"https://objectcontent.lgthinq.com/8cd1080c-3c86-45c5-ba15-e3e53c0f6b0d?hdnts=exp=1690436193~hmac=87f4cba3139bdbf4d52f5ed4fc15384043da8c87c0d471402e1c3eb6afb2acd1","appRestartYn":"Y","appModuleSize":"13511210","langPackProductTypeVer":"55.9","langPackProductTypeUri":"https://objectcontent.lgthinq.com/6c3fc08a-d6dc-4787-9264-ffe7f5c2b4d5?hdnts=exp=1698295253~hmac=1f6d024d4ebbc6ca759331b5835eab4f0561b43ac42b5f525550688eb0553236","langPackModelVer":"","langPackModelUri":"","roomId":"","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"2.6.2_RTOS_3K","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"P:SD","cardType":"Small","cardControl":"Base","upgradableYn":"N"}
10/30/2021, 4:22:03 PMLg Thinq BridgeLGThinQ[Office Air] Setting up device!
10/30/2021, 4:22:05 PMLg Thinq BridgeLGThinQ[request] post https://kic.lgthinq.com:46030/api/common/gatewayUriList
10/30/2021, 4:22:05 PMLg Thinq BridgeLGThinQ[request] post https://us.lgeapi.com/oauth2/token
10/30/2021, 4:22:06 PMLg Thinq BridgeLGThinQ[request] post https://aic.lgthinq.com:46030/api/member/login
10/30/2021, 4:22:07 PMLg Thinq BridgeLGThinQretried request error:  TokenExpiredError: Not logged in.
    at client.interceptors.response.use.err.response._a (/var/lib/hoobs/lgthinqbridge/node_modules/homebridge-lg-thinq/src/lib/request.ts:29:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at API.request (/var/lib/hoobs/lgthinqbridge/node_modules/homebridge-lg-thinq/src/lib/API.ts:57:12)
    at /var/lib/hoobs/lgthinqbridge/node_modules/homebridge-lg-thinq/src/lib/API.ts:63:18
    at /var/lib/hoobs/lgthinqbridge/node_modules/homebridge-lg-thinq/src/lib/API.ts:62:16
    at API.request (/var/lib/hoobs/lgthinqbridge/node_modules/homebridge-lg-thinq/src/lib/API.ts:57:12)
    at API.postRequest (/var/lib/hoobs/lgthinqbridge/node_modules/homebridge-lg-thinq/src/lib/API.ts:46:12)
    at API.thinq1PostRequest (/var/lib/hoobs/lgthinqbridge/node_modules/homebridge-lg-thinq/src/lib/API.ts:252:12)
    at API.sendMonitorCommand (/var/lib/hoobs/lgthinqbridge/node_modules/homebridge-lg-thinq/src/lib/API.ts:176:12)
    at ThinQ.registerWorkId (/var/lib/hoobs/lgthinqbridge/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:96:31)
    at ThinQ.setup (/var/lib/hoobs/lgthinqbridge/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:73:7)
    at LGThinQHomebridgePlatform.discoverDevices (/var/lib/hoobs/lgthinqbridge/node_modules/homebridge-lg-thinq/src/platform.ts:120:28)
10/30/2021, 4:22:07 PMLg Thinq BridgeLGThinQERRORCannot read property 'lgedmRoot' of undefined
10/30/2021, 4:22:07 PMLg Thinq BridgeLGThinQTypeError: Cannot read property 'lgedmRoot' of undefined
```

**Comment by nVuln** [comment]
I already published test version `v1.2.10-test.1` to fix this issue, can you try it ?

**Comment by mrfletch** [comment]
That did it, I can now see all 3 air conditioners in HomeKit and am able to turn them on/off and set the temperature. So that's perfect for me.

While looking at the logs I did notice some errors appear. Nothing that appears to be blocking operation, but just wanted to give you a heads up:

```
31/2021, 11:47:53 AMLg Thinq BridgeInitializing HAP-NodeJS v0.9.6...
10/31/2021, 11:47:57 AMLg Thinq BridgeLoaded plugin 'homebridge-lg-thinq'
10/31/2021, 11:47:57 AMLg Thinq BridgeRegistering platform 'homebridge-lg-thinq.LGThinQ'
10/31/2021, 11:47:57 AMLg Thinq BridgeLoading 1 platforms...
10/31/2021, 11:47:57 AMLg Thinq BridgePreparing Advertiser for 'Lg Thinq Bridge 3DB8' using bonjour-hap backend!
10/31/2021, 11:47:57 AMLg Thinq BridgeStarting to advertise 'Lg Thinq Bridge 3DB8' using bonjour-hap backend!
10/31/2021, 11:47:57 AMLg Thinq BridgeBridge is running on port 51836.
10/31/2021, 11:48:04 AMLg Thinq BridgeLGThinQSuccessfully connected to the ThinQ API.
10/31/2021, 11:48:06 AMLg Thinq BridgeLGThinQ[Office Air] Setting up device!
10/31/2021, 11:48:06 AMLg Thinq BridgeLGThinQAdding new accessory: d27af0a0-7149-11d3-80aa-a06faaeb886c: Office Air (AC POT_056905_WW)
10/31/2021, 11:48:07 AMLg Thinq BridgeLGThinQ[Bedroom Air] Setting up device!
10/31/2021, 11:48:09 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Office Air@Office Air@Target Heater-Cooler State] characteristic value 0 is not contained in valid values array
10/31/2021, 11:48:09 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Office Air@Office Air@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
10/31/2021, 11:48:09 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Office Air@Office Air@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 16
10/31/2021, 11:48:32 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Office Air@Office Air@Target Heater-Cooler State] characteristic value 0 is not contained in valid values array
10/31/2021, 11:48:32 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Office Air@Office Air@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
10/31/2021, 11:48:32 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Office Air@Office Air@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 16
10/31/2021, 11:49:10 AMLg Thinq BridgeLGThinQAdding new accessory: d27c0210-7149-11d3-80b1-7c1c4e8cde86: Bedroom Air (AC POT_056905_WW)
10/31/2021, 11:49:10 AMLg Thinq BridgeLGThinQ[Living Room Air] Setting up device!
10/31/2021, 11:49:11 AMLg Thinq BridgeLGThinQAdding new accessory: d2837c20-7149-11d3-80e2-044eaf3a5b66: Living Room Air (AC POT_056905_WW)
10/31/2021, 11:49:11 AMLg Thinq BridgeLGThinQStart polling device data every 60 second.
10/31/2021, 11:49:12 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Office Air@Office Air@Target Heater-Cooler State] characteristic value 0 is not contained in valid values array
10/31/2021, 11:49:12 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Office Air@Office Air@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
10/31/2021, 11:49:12 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Office Air@Office Air@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 16
10/31/2021, 11:49:12 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Bedroom Air@Bedroom Air@Target Heater-Cooler State] characteristic value 0 is not contained in valid values array
10/31/2021, 11:49:12 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Bedroom Air@Bedroom Air@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
10/31/2021, 11:49:12 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Bedroom Air@Bedroom Air@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 16
10/31/2021, 11:49:12 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Living Room Air@Living Room Air@Target Heater-Cooler State] characteristic value 0 is not contained in valid values array
10/31/2021, 11:49:12 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Living Room Air@Living Room Air@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
10/31/2021, 11:49:12 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Living Room Air@Living Room Air@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 16
10/31/2021, 11:49:48 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Office Air@Office Air@Target Heater-Cooler State] characteristic value 0 is not contained in valid values array
10/31/2021, 11:49:48 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Office Air@Office Air@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
10/31/2021, 11:49:48 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Office Air@Office Air@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 16
10/31/2021, 11:49:48 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Bedroom Air@Bedroom Air@Target Heater-Cooler State] characteristic value 0 is not contained in valid values array
10/31/2021, 11:49:48 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Bedroom Air@Bedroom Air@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
10/31/2021, 11:49:48 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Bedroom Air@Bedroom Air@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 16
10/31/2021, 11:49:48 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Living Room Air@Living Room Air@Target Heater-Cooler State] characteristic value 0 is not contained in valid values array
10/31/2021, 11:49:49 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Living Room Air@Living Room Air@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
10/31/2021, 11:49:49 AMLg Thinq BridgeERROR[Lg Thinq Bridge 3DB8@Living Room Air@Living Room Air@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 16
```

**Comment by nVuln** [comment]
Sorry for late reply, it's just a warning message, sometime you may got this warning because wrong data value, thinq1 device is very hard to handle it
please try restart and let see if you still got that warning message

**Comment by mrfletch** [comment]
Looks like we’re good, Siri is communicating well with the air conditioners. Really appreciate all your work on this project!
